// packages/react/src/components/listbox.tsx
import {
  listboxContract,
  listboxDefaultValue,
  listboxEvents,
  listboxParts,
  type ListboxItem,
  type ListboxOptions,
  type ListboxValueChangeDetails,
} from "@skryensya/core/listbox";
import { listbox } from "@skryensya/core/machines";
import { normalizeProps, useMachine } from "@zag-js/react";
import { useId, useMemo, useRef, type ReactNode } from "react";
import { Icon } from "./icon.js";

export type { ListboxItem, ListboxValueChangeDetails } from "@skryensya/core/listbox";

const { orientation: orientationOption, selectionMode: selectionModeOption } = listboxContract.options;

export type ListboxProps = {
  id?: string;
  /** What the list is a choice of. Visible, and the listbox's name. */
  label: ReactNode;
  items: readonly ListboxItem[];
  selectionMode?: ListboxOptions["selectionMode"];
  orientation?: ListboxOptions["orientation"];
  disabled?: boolean;
  /** Controlled selection. */
  value?: string[];
  /** Uncontrolled selection. Without it, every item marked `defaultSelected` starts chosen. */
  defaultValue?: string[];
  onValueChange?: (details: ListboxValueChangeDetails) => void;
  /** The check on a chosen option. Pass `null` for none. */
  itemIndicator?: ReactNode;
};

/** A list of options chosen from in place: always open, single or multiple. */
export function Listbox({
  id,
  label,
  items,
  selectionMode = selectionModeOption.default,
  orientation = orientationOption.default,
  disabled,
  value,
  defaultValue,
  onValueChange,
  itemIndicator,
}: ListboxProps) {
  const generatedId = useId();
  const rootRef = useRef<HTMLDivElement>(null);
  const collection = useMemo(
    () =>
      listbox.collection<ListboxItem>({
        items: [...items],
        itemToString: (item) => item.label,
        itemToValue: (item) => item.value,
        isItemDisabled: (item) => Boolean(item.disabled),
      }),
    [items],
  );

  const service = useMachine(listbox.machine, {
    id: id ?? generatedId,
    collection,
    selectionMode,
    orientation,
    disabled,
    /* Spread only when given: a `value` key that is present but undefined still reads as controlled
       to Zag's React adapter, and a click then changes nothing. */
    ...(value !== undefined ? { value } : {}),
    defaultValue: defaultValue ?? listboxDefaultValue(items),
    onValueChange(details: { value: string[] }) {
      const change: ListboxValueChangeDetails = { value: details.value };
      onValueChange?.(change);
      rootRef.current?.dispatchEvent(new CustomEvent(listboxEvents.valueChange, { bubbles: true, detail: change }));
    },
  });
  const api = listbox.connect(service, normalizeProps);

  return (
    <div
      {...api.getRootProps()}
      className={listboxParts.root}
      data-disabled={disabled ? "" : undefined}
      data-orientation={orientation}
      data-selection-mode={selectionMode}
      data-sk-listbox=""
      ref={rootRef}
    >
      <span {...api.getLabelProps()} className={listboxParts.label} data-sk-listbox-label="">
        {label}
      </span>
      <ul {...api.getContentProps()} className={listboxParts.content} data-sk-listbox-content="">
        {items.map((item) => (
          <li
            {...api.getItemProps({ item })}
            className={`${listboxParts.item} sk-interactive`}
            data-default-selected={item.defaultSelected ? "" : undefined}
            data-sk-listbox-item=""
            key={item.value}
          >
            <span {...api.getItemTextProps({ item })} className={listboxParts.itemText} data-sk-listbox-item-text="">
              {item.label}
            </span>
            <span
              {...api.getItemIndicatorProps({ item })}
              aria-hidden="true"
              className={listboxParts.itemIndicator}
              data-sk-listbox-item-indicator=""
            >
              {itemIndicator === undefined ? <Icon name="check" /> : itemIndicator}
            </span>
          </li>
        ))}
      </ul>
    </div>
  );
}

// packages/vanilla/src/components/Listbox.svelte
<script lang="ts">
  import {
    listboxAttrs,
    listboxDefaultValue,
    listboxEvents,
    type ListboxItem,
    type ListboxOptions,
    type ListboxValueChangeDetails,
  } from "@skryensya/core/listbox";
  import { listbox } from "@skryensya/core/machines";
  import { selectorsFor } from "@skryensya/core/selectors";
  import { normalizeProps, useMachine } from "@zag-js/svelte";
  import { bindParts, type PartBinding } from "../runtime/bind-part.svelte";
  import { getRoot, uniqueId } from "../runtime/svelte-hydrate";

  /*
   * LISTBOX, a machine-backed enhancer over `@zag-js/listbox` (the SAME machine React uses). It
   * renders nothing: the options are the authored `[data-sk-listbox-item]` rows, read once into the
   * machine's collection, and every patch after that is Zag's props on the nodes already there.
   */
  const root = getRoot();
  const selector = selectorsFor(listboxAttrs);

  const content = root.querySelector<HTMLElement>(selector.content);
  const label = root.querySelector<HTMLElement>(selector.label);
  const itemEls = Array.from(root.querySelectorAll<HTMLElement>(selector.item));

  if (!content) throw new Error("Listbox requires a [data-sk-listbox-content] element.");
  if (itemEls.length === 0) throw new Error("Listbox requires at least one [data-sk-listbox-item].");

  function readItem(el: HTMLElement): ListboxItem {
    const value = el.dataset.value;
    if (!value) throw new Error("Every [data-sk-listbox-item] needs a non-empty data-value.");
    const text = el.querySelector<HTMLElement>(selector.itemText) ?? el;
    return {
      value,
      label: text.textContent?.trim() || value,
      disabled: el.hasAttribute("data-disabled"),
      defaultSelected: el.hasAttribute("data-default-selected"),
    };
  }

  const items = itemEls.map(readItem);
  const collection = listbox.collection<ListboxItem>({
    items,
    itemToString: (item) => item.label,
    itemToValue: (item) => item.value,
    isItemDisabled: (item) => Boolean(item.disabled),
  });

  if (!root.id) root.id = uniqueId("sk-listbox");

  const authoredMode = root.dataset.selectionMode;
  const selectionMode: ListboxOptions["selectionMode"] =
    authoredMode === "multiple" || authoredMode === "extended" ? authoredMode : "single";
  const orientation: ListboxOptions["orientation"] =
    root.dataset.orientation === "horizontal" ? "horizontal" : "vertical";

  const service = useMachine(listbox.machine, () => ({
    id: root.id,
    ids: { label: label?.id || undefined, content: content.id || undefined },
    collection,
    selectionMode,
    orientation,
    disabled: root.hasAttribute("data-disabled"),
    defaultValue: listboxDefaultValue(items),
    onValueChange(details: { value: string[] }) {
      root.dispatchEvent(
        new CustomEvent<ListboxValueChangeDetails>(listboxEvents.valueChange, {
          bubbles: true,
          detail: { value: details.value },
        }),
      );
    },
  }));
  const api = $derived(listbox.connect(service, normalizeProps));

  const bindings: PartBinding[] = [
    { part: "root", node: () => root, props: () => api.getRootProps() },
    { part: "label", node: () => label, props: () => api.getLabelProps() },
    { part: "content", node: () => content, props: () => api.getContentProps(), events: true },
    ...itemEls.flatMap((el, index): PartBinding[] => {
      const item = items[index]!;
      return [
        { part: "item", node: () => el, props: () => api.getItemProps({ item }), events: true, classes: ["sk-interactive"] },
        {
          part: "itemText",
          node: () => el.querySelector<HTMLElement>(selector.itemText),
          props: () => api.getItemTextProps({ item }),
        },
        {
          part: "itemIndicator",
          node: () => el.querySelector<HTMLElement>(selector.itemIndicator),
          props: () => api.getItemIndicatorProps({ item }),
        },
      ];
    }),
  ];

  bindParts(bindings);
</script>
