// packages/vanilla/src/components/Carousel.svelte
<script lang="ts">
  import { carousel } from "@skryensya/core/machines";
  import { carouselEvents, carouselParts, carouselTranslations, type CarouselGotoDetail } from "@skryensya/core/carousel";
  import { normalizeProps, useMachine } from "@zag-js/svelte";
  import { onDestroy, onMount } from "svelte";
  import { bindParts, type PartBinding } from "../runtime/bind-part.svelte";
  import { getRoot, uniqueId } from "../runtime/svelte-hydrate";
  import { remountIcons } from "../icon.js";

  /*
   * CAROUSEL, a machine-backed enhancer over `@zag-js/carousel`.
   *
   * It splits the work by owner: the TRACK and the SLIDES are authored markup, so they are scanned and
   * patched with the machine's attributes (same as Tabs). The CONTROLS are not content but chrome
   * derived from the track, so this component renders them, like the old enhancer, and for the same
   * reason they cannot be authored: how many dots there are is not known by whoever writes the HTML.
   * The machine knows, and only after MEASURING.
   *
   * That is the bug the machine fixes. The real snap points are not one per slide: with slides that
   * peek, the last ones all clamp against the maximum scroll and collapse onto the same position. The
   * old enhancer drew one dot per slide and called `scrollTo(slide.offsetLeft)`, so the last dots could
   * not be activated and the "next" button never disabled itself. Zag derives the pages from
   * `getScrollSnapPositions` (measured, clamped and deduplicated), which is why the dots here come from
   * `api.pageSnapPoints` and not from the number of slides.
   *
   * A slide's size still belongs to CSS (`--sk-carousel-slide-size`), not to the machine: with
   * `autoSize` Zag imposes no widths, it only measures. That way the no-JS layer and the enhanced one
   * are the SAME carousel, and the machine does not become the owner of the layout.
   */
  const root = getRoot();

  const track = root.querySelector<HTMLElement>(`.${carouselParts.track}`);
  if (!track) throw new Error(`[data-sk-carousel] necesita una pista .${carouselParts.track}.`);
  const slides = Array.from(track.querySelectorAll<HTMLElement>(`.${carouselParts.slide}`));

  if (!root.id) root.id = uniqueId("sk-carousel");
  const ids = {
    root: root.id,
    itemGroup: `${root.id}-track`,
    item: (index: number) => `${root.id}-slide-${index}`,
    prevTrigger: `${root.id}-prev`,
    nextTrigger: `${root.id}-next`,
    indicatorGroup: `${root.id}-dots`,
    indicator: (index: number) => `${root.id}-dot-${index}`,
  };

  // The machine starts its effects (mutation/resize/intersection observers) and its `setSnapPoints`
  // entry BEFORE the first `$effect` runs, and for that it resolves the track by id and the slides by
  // `[data-part=item]`. They are seeded here, in the script body, so they are already there when it measures.
  track.id = ids.itemGroup;
  track.setAttribute("data-scope", "carousel");
  track.setAttribute("data-part", "itemGroup");
  slides.forEach((slide, index) => {
    slide.id = ids.item(index);
    slide.setAttribute("data-scope", "carousel");
    slide.setAttribute("data-part", "item");
    slide.setAttribute("data-index", String(index));
    // The same, but for style: the first measurement reads the COMPUTED `scroll-snap-align` to know
    // where each slide anchors. The system's sheet already declares it, but a consumer may mount without
    // that CSS, and then the machine would not find a single snap point. It is the same value Zag writes.
    slide.style.setProperty("scroll-snap-align", "start");
  });

  /*
   * Autoplay, with the brake on by default: whoever asked for less motion does not get a carousel that
   * moves on its own. The option stays declared anyway, so if the user changes their preference the
   * markup does not lie; it simply does not start here.
   */
  const prefersReducedMotion = window.matchMedia?.("(prefers-reduced-motion: reduce)").matches ?? false;
  const autoplayAttr = root.getAttribute("data-autoplay");
  const autoplayDelay = Number(autoplayAttr);
  const wantsAutoplay = autoplayAttr !== null;
  const autoplay =
    !wantsAutoplay || prefersReducedMotion
      ? false
      : Number.isFinite(autoplayDelay) && autoplayDelay > 0
        ? { delay: autoplayDelay }
        : true;

  const service = useMachine(carousel.machine, () => ({
    id: root.id,
    ids,
    slideCount: slides.length,
    orientation: (root.getAttribute("data-orientation") === "vertical" ? "vertical" : "horizontal") as
      | "vertical"
      | "horizontal",
    dir: (root.closest("[dir=rtl]") ? "rtl" : "ltr") as "ltr" | "rtl",
    loop: root.hasAttribute("data-loop"),
    autoplay,
    // ON by default. A vertical wheel scrolls the PAGE, not a horizontal track, so a mouse has no
    // other way through: without this a desktop pointer cannot move a carousel that has no controls.
    // `data-mouse-drag="off"` opts out, for slides whose text is meant to be selectable.
    allowMouseDrag: root.getAttribute("data-mouse-drag") !== "off",
    // A slide's width is set by the system's CSS; the machine only measures where each snap point falls.
    autoSize: true,
    spacing: "var(--sk-carousel-gap)",
    translations: carouselTranslations,
  }));

  const api = $derived(carousel.connect(service, normalizeProps));

  /*
   * WCAG 2.2.2 (Pause, Stop, Hide) and the WAI-ARIA Carousel pattern ask that automatic rotation stop
   * as soon as the mouse passes over it OR the keyboard enters with focus, and resume on leaving -
   * unless the OTHER condition is still active. Zag's machine (1.42.0) implements neither: its
   * `autoplay` state does not react at all to `VIEWPORT.FOCUS` (confirmed by reading
   * `carousel.machine.js`), and there is no mouseenter/mouseleave handling anywhere in the package.
   *
   * `desiredPlaying` is the user's explicit intent. What the pause/play button last asked for.
   * Independent of the TEMPORARY pause that hover/focus impose. Without that separation, moving the
   * mouse out would resume a carousel the user stopped on purpose with the button.
   */
  let hovering = $state(false);
  let focused = $state(false);
  let desiredPlaying = $state(Boolean(autoplay));

  $effect(() => {
    if (!wantsAutoplay) return;
    const shouldPlay = desiredPlaying && !hovering && !focused;
    if (shouldPlay === api.isPlaying) return;
    if (shouldPlay) api.play();
    else api.pause();
  });

  /*
   * Three reasons not to draw controls, and all three are the same one: there is nothing to control.
   *   - `data-controls="none"`, the consumer asked for it: the track stays a snap scroller, dragged or
   *     swiped, and the peek of the next slide is the only thing that announces it.
   *   - A single slide, which is not a carousel.
   *   - A single measured page, meaning everything fits at once and there is nowhere to go.
   */
  const wantsControls = root.getAttribute("data-controls") !== "none";
  const showControls = $derived(wantsControls && slides.length > 1 && api.pageSnapPoints.length > 1);

  /*
   * `connect`'s STYLES are written once; its ATTRIBUTES, on every state change.
   *
   * The style Zag returns here is static configuration (display, gap, snap type, overflow, a slide's
   * width), derived from props that do not change over the component's life. The attributes are not:
   * `data-dragging`, `data-inview`, `aria-hidden` are state and have to follow it.
   *
   * And re-applying the style is actively harmful, because the machine also writes styles by hand: when
   * a drag starts it sets `scroll-snap-type: none` so it can move the track. If the effect returns it to
   * `x mandatory` in the same frame, the browser re-snaps on every dragged pixel and moving the mouse
   * 10px jumps a whole slide. The configuration is ours, the state is the machine's.
   */
  const bindings: PartBinding[] = [
    { part: "root", node: () => root, props: () => api.getRootProps(), style: "once" },
    {
      part: "itemGroup",
      node: () => track,
      props: () => api.getItemGroupProps(),
      style: "once",
      events: true,
    },
    ...slides.map((slide, index): PartBinding => ({
      part: "item",
      node: () => slide,
      props: () => api.getItemProps({ index }),
      style: "once",
    })),
  ];

  bindParts(bindings);

  /*
   * The public event contract, untouched: `sk:carouselchange` on page change (by scroll, button, key,
   * drag or goto) and `sk:carouselgoto` as an input command. `index` is the PAGE, which with the
   * default of one slide per page is the slide's index.
   */
  let lastPage = -1;
  $effect(() => {
    const index = api.page;
    const count = api.pageSnapPoints.length;
    if (index === lastPage) return;
    const isInitial = lastPage === -1;
    lastPage = index;
    if (isInitial) return;
    root.dispatchEvent(new CustomEvent(carouselEvents.change, { bubbles: true, detail: { index, count } }));
  });

  const cleanups: Array<() => void> = [];
  onMount(() => {
    const onGoto = ((event: CustomEvent<CarouselGotoDetail>) => {
      const index = event.detail?.index ?? 0;
      // Asking for the page you are already on does not move the machine, so it would not move the scroll
      // either. `refresh` re-measures and re-aligns, which is what a goto to the current page has to mean.
      if (index === api.page) api.refresh();
      else api.scrollTo(index);
    }) as EventListener;
    root.addEventListener(carouselEvents.goto, onGoto);
    cleanups.push(() => root.removeEventListener(carouselEvents.goto, onGoto));

    // Root-level: "hovering" is any point of the carousel, not just the track, and `focusin`/`focusout`
    // (unlike `focus`/`blur`) bubble, so a single listener detects focus on ANY descendant (a slide, the
    // prev/next, a dot) without having to capture on each one separately.
    if (wantsAutoplay) {
      const onMouseEnter = () => {
        hovering = true;
      };
      const onMouseLeave = () => {
        hovering = false;
      };
      const onFocusIn = () => {
        focused = true;
      };
      const onFocusOut = (event: FocusEvent) => {
        if (root.contains(event.relatedTarget as Node | null)) return;
        focused = false;
      };
      root.addEventListener("mouseenter", onMouseEnter);
      root.addEventListener("mouseleave", onMouseLeave);
      root.addEventListener("focusin", onFocusIn);
      root.addEventListener("focusout", onFocusOut);
      cleanups.push(() => {
        root.removeEventListener("mouseenter", onMouseEnter);
        root.removeEventListener("mouseleave", onMouseLeave);
        root.removeEventListener("focusin", onFocusIn);
        root.removeEventListener("focusout", onFocusOut);
      });
    }

    // The chevrons are authored as `data-sk-icon` placeholders and hydrated by the set the app already
    // registered with `mountIcons` (ADR-15: the set stays explicit on the app's side).
    remountIcons(root);

    // Re-measure once the DOM has been patched and the controls rendered: the machine's first
    // measurement runs before the `$effect`, and the height of the controls row changes the box.
    api.refresh();
  });
  onDestroy(() => {
    for (const cleanup of cleanups) cleanup();
  });
</script>

{#if showControls}
  <div class={carouselParts.controls} {...api.getControlProps()}>
    <button {...api.getPrevTriggerProps()} class="{carouselParts.button} sk-interactive">
      <span data-sk-icon="chevron-left" data-sk-icon-size="sm"></span>
    </button>

    <div class={carouselParts.dots} {...api.getIndicatorGroupProps()}>
      {#each api.pageSnapPoints as _, index (index)}
        <button
          {...api.getIndicatorProps({ index })}
          class="{carouselParts.dot} sk-interactive"
          aria-current={index === api.page ? "true" : undefined}
        ></button>
      {/each}
    </div>

    <button {...api.getNextTriggerProps()} class="{carouselParts.button} sk-interactive">
      <span data-sk-icon="chevron-right" data-sk-icon-size="sm"></span>
    </button>

    <!-- The glyph is drawn by CSS from `data-pressed`, not an icon: pause/play are not in the stable
         vocabulary of roles, and this is not reason enough to force every set to draw them. -->
    {#if wantsAutoplay}
      <!--
        `data-pressed` and `aria-label` do NOT come from Zag's spread (which derives them from
        `api.isPlaying`, the MOMENTARY state. Suppressed while the mouse or the focus is over it). They
        come from `desiredPlaying`, the user's last EXPLICIT choice: if the button showed "Resume" just
        because hover had already paused the rotation, a click there would do the opposite of what it
        promises (it would restart instead of stop). The `onclick` does not delegate to Zag's either, for
        the same reason: it only toggles `desiredPlaying`, and the effect above is the only one that
        calls play()/pause().
      -->
      <button
        {...api.getAutoplayTriggerProps()}
        class="{carouselParts.button} {carouselParts.autoplay} sk-interactive"
        data-pressed={desiredPlaying ? "" : undefined}
        aria-label={desiredPlaying ? carouselTranslations.autoplayStop : carouselTranslations.autoplayStart}
        onclick={(event) => {
          if (event.defaultPrevented) return;
          desiredPlaying = !desiredPlaying;
        }}
      ></button>
    {/if}
  </div>
{/if}

// packages/react/src/components/carousel.tsx
import {
  carouselContract,
  carouselEvents,
  carouselParts,
  carouselTranslations,
  type CarouselChangeDetail,
  type CarouselGotoDetail,
} from "@skryensya/core/carousel";
import type { OptionValue } from "@skryensya/core/contract";
import { carousel } from "@skryensya/core/machines";
import { normalizeProps, useMachine } from "@zag-js/react";
import {
  Children,
  createContext,
  forwardRef,
  isValidElement,
  useContext,
  useEffect,
  useId,
  useImperativeHandle,
  useRef,
  useState,
  type CSSProperties,
  type HTMLAttributes,
  type ReactNode,
} from "react";
import { Icon } from "./icon.js";

/* Derived, never restated: the default lives in the contract. */
const { mounted: mountedOption } = carouselContract.options;

const cx = (base: string, className: string | undefined) => (className ? `${base} ${className}` : base);

export type CarouselHandle = {
  /** Snap to a page index. Dispatches the same goto command any consumer can dispatch. */
  snapTo: (index: number) => void;
  /** The carousel root element, or null before mount. */
  element: HTMLElement | null;
};

export type CarouselProps = HTMLAttributes<HTMLElement> & {
  children: ReactNode;
  /** Names the carousel region for assistive tech. */
  "aria-label"?: string;
  loop?: boolean;
  /** Advance on a timer. Also draws the pause control, which WCAG 2.2.2 requires along with it. */
  autoplay?: boolean | number;
  orientation?: OptionValue<typeof carouselContract.options.orientation>;
  controls?: OptionValue<typeof carouselContract.options.controls>;
  mouseDrag?: OptionValue<typeof carouselContract.options.mouseDrag>;
  /** Set false to leave the native CSS-only scroll-snap baseline unenhanced. */
  mounted?: boolean;
  /** CSS length for each slide, e.g. `min(42%, 14rem)`. */
  slideSize?: string;
};

type CarouselApi = ReturnType<typeof carousel.connect>;

/* The machine for the slides below, and each slide's index. Null outside a mounted Carousel, where a
 * slide is the plain scroll-snap item the zero-JS baseline draws. */
const CarouselApiContext = createContext<CarouselApi | null>(null);
const CarouselIndexContext = createContext<number>(-1);

/*
 * CAROUSEL, the same `@zag-js/carousel` machine the vanilla enhancer runs, configured the same way
 * (`Carousel.svelte` has the reasoning behind every setting). React used to render only the static
 * markup and wait for the vanilla enhancer to find it, which left a React app without the vanilla
 * runtime with no controls at all.
 *
 * `mounted={false}` is the zero-JS baseline: the section and the track, no machine.
 */
export const Carousel = forwardRef<CarouselHandle, CarouselProps>(function Carousel(
  { mounted = mountedOption.default, ...props },
  ref,
) {
  return mounted ? <MountedCarousel {...props} handleRef={ref} /> : <StaticCarousel {...props} handleRef={ref} />;
});

type InnerProps = Omit<CarouselProps, "mounted"> & { handleRef: React.ForwardedRef<CarouselHandle> };

function useCarouselHandle(handleRef: InnerProps["handleRef"], rootRef: React.RefObject<HTMLElement | null>) {
  useImperativeHandle(
    handleRef,
    () => ({
      element: rootRef.current,
      snapTo: (index: number) => {
        const detail: CarouselGotoDetail = { index };
        rootRef.current?.dispatchEvent(new CustomEvent(carouselEvents.goto, { detail }));
      },
    }),
    [rootRef],
  );
}

function rootAttributes({ autoplay, controls, loop, mouseDrag, orientation }: InnerProps) {
  return {
    "data-autoplay": typeof autoplay === "number" ? autoplay : autoplay ? "" : undefined,
    "data-controls": controls,
    "data-loop": loop ? "" : undefined,
    "data-mouse-drag": mouseDrag,
    "data-orientation": orientation,
  };
}

function StaticCarousel(inner: InnerProps) {
  const { autoplay, children, className, controls, handleRef, loop, mouseDrag, orientation, slideSize, style, ...props } =
    inner;
  const rootRef = useRef<HTMLElement>(null);
  useCarouselHandle(handleRef, rootRef);

  return (
    <section
      {...props}
      {...rootAttributes(inner)}
      className={cx(carouselParts.root, className)}
      ref={rootRef}
      style={slideSize ? { ...style, "--sk-carousel-slide-size": slideSize } as CSSProperties : style}
    >
      {/* A div, not a <ul>: the machine gives each slide role="group", which takes it out of the
          list and leaves a list with no list items. */}
      <div className={carouselParts.track}>{children}</div>
    </section>
  );
}

function prefersReducedMotion(): boolean {
  return typeof window !== "undefined" && (window.matchMedia?.("(prefers-reduced-motion: reduce)").matches ?? false);
}

function MountedCarousel(inner: InnerProps) {
  const { autoplay, children, className, controls, dir, handleRef, id, loop, mouseDrag, orientation, slideSize, style, ...props } =
    inner;
  const generatedId = useId();
  const rootId = id ?? generatedId;
  const rootRef = useRef<HTMLElement>(null);
  useCarouselHandle(handleRef, rootRef);

  const slides = Children.toArray(children).filter(isValidElement);
  const ids = {
    root: rootId,
    itemGroup: `${rootId}-track`,
    item: (index: number) => `${rootId}-slide-${index}`,
    prevTrigger: `${rootId}-prev`,
    nextTrigger: `${rootId}-next`,
    indicatorGroup: `${rootId}-dots`,
    indicator: (index: number) => `${rootId}-dot-${index}`,
  };

  /* Autoplay, with the brake on: whoever asked for less motion does not get a carousel that moves. */
  const wantsAutoplay = autoplay !== undefined && autoplay !== false;
  const [initialAutoplay] = useState(() =>
    !wantsAutoplay || prefersReducedMotion()
      ? false
      : typeof autoplay === "number" && autoplay > 0
        ? { delay: autoplay }
        : true,
  );

  const service = useMachine(carousel.machine, {
    id: rootId,
    ids,
    slideCount: slides.length,
    orientation: orientation === "vertical" ? "vertical" : "horizontal",
    dir: dir === "rtl" ? "rtl" : "ltr",
    loop: Boolean(loop),
    autoplay: initialAutoplay,
    allowMouseDrag: mouseDrag !== "off",
    autoSize: true,
    spacing: "var(--sk-carousel-gap)",
    translations: carouselTranslations,
  });
  const api = carousel.connect(service, normalizeProps);
  const apiRef = useRef(api);
  apiRef.current = api;

  /*
   * Hover and focus pause the rotation and leaving resumes it, unless the other one still holds or
   * the reader stopped it with the button (`desiredPlaying`). Zag's machine does neither; see
   * `Carousel.svelte` for the WCAG 2.2.2 reasoning.
   */
  const [hovering, setHovering] = useState(false);
  const [focused, setFocused] = useState(false);
  const [desiredPlaying, setDesiredPlaying] = useState(Boolean(initialAutoplay));

  useEffect(() => {
    if (!wantsAutoplay) return;
    const shouldPlay = desiredPlaying && !hovering && !focused;
    if (shouldPlay === api.isPlaying) return;
    if (shouldPlay) api.play();
    else api.pause();
  }, [api, desiredPlaying, focused, hovering, wantsAutoplay]);

  useEffect(() => {
    const root = rootRef.current;
    if (!root || !wantsAutoplay) return;
    const onMouseEnter = () => setHovering(true);
    const onMouseLeave = () => setHovering(false);
    const onFocusIn = () => setFocused(true);
    const onFocusOut = (event: FocusEvent) => {
      if (!root.contains(event.relatedTarget as Node | null)) setFocused(false);
    };
    root.addEventListener("mouseenter", onMouseEnter);
    root.addEventListener("mouseleave", onMouseLeave);
    root.addEventListener("focusin", onFocusIn);
    root.addEventListener("focusout", onFocusOut);
    return () => {
      root.removeEventListener("mouseenter", onMouseEnter);
      root.removeEventListener("mouseleave", onMouseLeave);
      root.removeEventListener("focusin", onFocusIn);
      root.removeEventListener("focusout", onFocusOut);
    };
  }, [wantsAutoplay]);

  /* The public event contract: `sk:carouselchange` on page change, `sk:carouselgoto` as input. */
  const lastPage = useRef(-1);
  useEffect(() => {
    const index = api.page;
    if (index === lastPage.current) return;
    const isInitial = lastPage.current === -1;
    lastPage.current = index;
    if (isInitial) return;
    const detail: CarouselChangeDetail = { index, count: api.pageSnapPoints.length };
    rootRef.current?.dispatchEvent(new CustomEvent(carouselEvents.change, { bubbles: true, detail }));
  }, [api.page, api.pageSnapPoints.length]);

  useEffect(() => {
    const root = rootRef.current;
    if (!root) return;
    const onGoto = ((event: CustomEvent<CarouselGotoDetail>) => {
      const index = event.detail?.index ?? 0;
      // A goto to the current page does not move the machine; `refresh` re-measures and re-aligns.
      if (index === apiRef.current.page) apiRef.current.refresh();
      else apiRef.current.scrollTo(index);
    }) as EventListener;
    root.addEventListener(carouselEvents.goto, onGoto);
    // Re-measure once the controls row exists: its height changes the box the first measure saw.
    apiRef.current.refresh();
    return () => root.removeEventListener(carouselEvents.goto, onGoto);
  }, []);

  /*
   * The same lifecycle mark the vanilla runtime writes, and it is not bookkeeping here: the sheet
   * shows the native zero-JS controls until it is present, and gates mouse drag on it. Without it
   * React drew both sets of controls at once.
   */
  const [ready, setReady] = useState(false);
  useEffect(() => setReady(true), []);

  const rootProps = api.getRootProps();
  const showControls = controls !== "none" && slides.length > 1 && api.pageSnapPoints.length > 1;

  return (
    <section
      {...props}
      {...rootProps}
      {...rootAttributes(inner)}
      className={cx(carouselParts.root, className)}
      data-sk-carousel=""
      data-sk-carousel-ready={ready ? "true" : undefined}
      ref={rootRef}
      style={{
        ...(rootProps.style as CSSProperties),
        ...style,
        ...(slideSize ? { "--sk-carousel-slide-size": slideSize } : null),
      } as CSSProperties}
    >
      <CarouselApiContext.Provider value={api}>
        <div {...api.getItemGroupProps()} className={carouselParts.track}>
          {slides.map((slide, index) => (
            <CarouselIndexContext.Provider key={slide.key ?? index} value={index}>
              {slide}
            </CarouselIndexContext.Provider>
          ))}
        </div>
      </CarouselApiContext.Provider>
      {showControls ? (
        <div {...api.getControlProps()} className={carouselParts.controls}>
          <button {...api.getPrevTriggerProps()} className={`${carouselParts.button} sk-interactive`}>
            <Icon name="chevron-left" size="sm" />
          </button>
          <div {...api.getIndicatorGroupProps()} className={carouselParts.dots}>
            {api.pageSnapPoints.map((_, index) => (
              <button
                {...api.getIndicatorProps({ index })}
                aria-current={index === api.page ? "true" : undefined}
                className={`${carouselParts.dot} sk-interactive`}
                key={index}
              />
            ))}
          </div>
          <button {...api.getNextTriggerProps()} className={`${carouselParts.button} sk-interactive`}>
            <Icon name="chevron-right" size="sm" />
          </button>
          {/* The glyph is CSS, drawn from `data-pressed`. Its state and label follow the reader's last
              explicit choice, not Zag's momentary `isPlaying` (see `Carousel.svelte`). */}
          {wantsAutoplay ? (
            <button
              {...api.getAutoplayTriggerProps()}
              aria-label={desiredPlaying ? carouselTranslations.autoplayStop : carouselTranslations.autoplayStart}
              className={`${carouselParts.button} ${carouselParts.autoplay} sk-interactive`}
              data-pressed={desiredPlaying ? "" : undefined}
              onClick={(event) => {
                if (event.defaultPrevented) return;
                setDesiredPlaying((playing) => !playing);
              }}
            />
          ) : null}
        </div>
      ) : null}
    </section>
  );
}

export type CarouselSlideProps = HTMLAttributes<HTMLDivElement> & {
  children: ReactNode;
};

/** One slide. Any content: a Card, an image, a stat; the track snaps to its start edge. */
export function CarouselSlide({ children, className, ...props }: CarouselSlideProps) {
  const api = useContext(CarouselApiContext);
  const index = useContext(CarouselIndexContext);
  const itemProps = api && index >= 0 ? api.getItemProps({ index }) : null;
  return (
    <div
      {...props}
      {...itemProps}
      className={cx(carouselParts.slide, className)}
      /* `scroll-snap-align` first, as the enhancer seeds it before the machine's first measure: that
         measure reads the computed value, and a consumer may mount without the system's sheet. */
      style={itemProps ? { scrollSnapAlign: "start", ...(itemProps.style as CSSProperties), ...props.style } : props.style}
    >
      {children}
    </div>
  );
}
