// packages/vanilla/src/components/Combobox.svelte
<script lang="ts">
  import {
    anchorNameFor,
    bindAnchor,
    stripPositioningStyle,
    supportsAnchorPositioning,
  } from "@skryensya/core/anchored";
  import { combobox } from "@skryensya/core/machines";
  import { comboboxParts, type ComboboxItem } from "@skryensya/core/combobox";
  import { normalizeProps, useMachine } from "@zag-js/svelte";
  import { onDestroy, onMount } from "svelte";
  import { applyZagProps, bindZagEvents, type DomProps } from "../runtime/apply";
  import { getRoot, uniqueId } from "../runtime/svelte-hydrate";

  /*
   * COMBOBOX, a machine-backed enhancer over `@zag-js/combobox` (the SAME machine React uses, via
   * `@skryensya/core/machines`). It renders no structure: it scans its authored markup and patches the
   * attributes `connect` returns onto those nodes. The filter runs over the AUTHORED items (the DOM
   * stays the source of truth), never over a list the binding invents.
   */
  const root = getRoot();

  const selector = {
    label: "[data-sk-combobox-label]",
    hint: "[data-sk-combobox-hint]",
    error: "[data-sk-combobox-error]",
    control: "[data-sk-combobox-control]",
    value: "[data-sk-combobox-value]",
    selectedItems: "[data-sk-combobox-selected-items]",
    removeTrigger: "[data-sk-combobox-remove-trigger]",
    input: "[data-sk-combobox-input]",
    trigger: "[data-sk-combobox-trigger]",
    clear: "[data-sk-combobox-clear]",
    positioner: "[data-sk-combobox-positioner]",
    content: "[data-sk-combobox-content]",
    item: "[data-sk-combobox-item]",
    itemText: "[data-sk-combobox-item-text]",
    itemIndicator: "[data-sk-combobox-item-indicator]",
    empty: "[data-sk-combobox-empty]",
    status: "[data-sk-combobox-status]",
  } as const;

  // The keys that move the highlight inside the listbox (the same ones the machine handles).
  const navigationKeys = new Set(["ArrowDown", "ArrowUp", "Home", "End", "PageUp", "PageDown"]);
  const combiningMarks = /\p{M}+/gu;
  const searchKey = (value: string) => value.normalize("NFD").replace(combiningMarks, "").toLocaleLowerCase();

  /*
   * The text of a button, as a NAME rather than as characters. `textContent` produces the icon on
   * an icon-only control (the chevron/clear glyphs sit inside `aria-hidden="true"` precisely to say
   * they are decoration).
   */
  const nameText = (element: Element): string => {
    let text = "";
    for (const node of element.childNodes) {
      if (node.nodeType === Node.TEXT_NODE) text += node.textContent ?? "";
      else if (
        node.nodeType === Node.ELEMENT_NODE &&
        (node as Element).getAttribute("aria-hidden") !== "true" &&
        !(node as Element).hasAttribute("hidden")
      )
        text += nameText(node as Element);
    }
    return text.trim();
  };
  const fromTemplate = (template: string, values: Record<string, string>) => {
    let result = template;
    for (const [key, value] of Object.entries(values)) result = result.replace(`{${key}}`, value);
    return result;
  };

  const label = root.querySelector<HTMLElement>(selector.label);
  const hint = root.querySelector<HTMLElement>(selector.hint);
  const error = root.querySelector<HTMLElement>(selector.error);
  const control = root.querySelector<HTMLElement>(selector.control);
  const input = root.querySelector<HTMLInputElement>(selector.input);
  const trigger = root.querySelector<HTMLElement>(selector.trigger);
  const clear = root.querySelector<HTMLButtonElement>(selector.clear);
  const positioner = root.querySelector<HTMLElement>(selector.positioner);
  const content = root.querySelector<HTMLElement>(selector.content);

  const ready = Boolean(label && control && input && trigger && positioner && content);

  // Captured ONCE, never re-read from the DOM: `getRootProps().id` returns a namespaced id
  // (`combobox:${id}`) and `applyZagProps` writes it back onto `root.id`. Reading `root.id` live from
  // `useMachine`'s reactive factory would feed that prefix back on every recomputation
  // (`combobox:combobox:combobox:…`), which is exactly what made the id grow without bound. The
  // imperative original never mutated `root.id`; this reproduces the same thing.
  const machineId = root.id || uniqueId("sk-combobox");

  /* The Anchoring pattern (ADR-25). The anchor is the whole CONTROL, not the chevron: the list lines up
   * with the field being typed into. */
  const anchorName = supportsAnchorPositioning() ? anchorNameFor(machineId) : null;
  let unbindAnchor: (() => void) | undefined;

  let valueArea = root.querySelector<HTMLElement>(selector.value);
  if (ready && input && !valueArea) {
    valueArea = document.createElement("div");
    valueArea.className = comboboxParts.value;
    valueArea.setAttribute("data-sk-combobox-value", "");
    input.before(valueArea);
    valueArea.append(input);
  }
  let selectedItemsEl = root.querySelector<HTMLElement>(selector.selectedItems);
  if (ready && root.hasAttribute("data-multiple") && !selectedItemsEl && valueArea) {
    selectedItemsEl = document.createElement("div");
    selectedItemsEl.className = comboboxParts.selectedItems;
    selectedItemsEl.setAttribute("data-sk-combobox-selected-items", "");
    valueArea.prepend(selectedItemsEl);
  }
  if (selectedItemsEl) {
    selectedItemsEl.setAttribute("role", "list");
    selectedItemsEl.setAttribute("aria-label", root.dataset.selectedLabel ?? "Valores seleccionados");
  }

  let emptyEl = root.querySelector<HTMLElement>(selector.empty);
  if (ready && content && !emptyEl) {
    emptyEl = document.createElement("div");
    emptyEl.className = comboboxParts.empty;
    emptyEl.setAttribute("data-sk-combobox-empty", "");
    emptyEl.textContent = root.dataset.emptyLabel ?? "Sin resultados";
    content.append(emptyEl);
  }
  emptyEl?.setAttribute("role", "presentation");

  let statusEl = root.querySelector<HTMLElement>(selector.status);
  if (ready && control && !statusEl) {
    statusEl = document.createElement("div");
    statusEl.className = `${comboboxParts.status} sk-visually-hidden`;
    statusEl.setAttribute("data-sk-combobox-status", "");
    statusEl.setAttribute("role", "status");
    statusEl.setAttribute("aria-atomic", "true");
    control.after(statusEl);
  }

  const invalid = input?.getAttribute("aria-invalid") === "true" || root.hasAttribute("data-invalid") || Boolean(error);
  const describedBy = [
    input?.getAttribute("aria-describedby"),
    hint ? (hint.id ||= `${machineId}:hint`) : undefined,
    error ? (error.id ||= `${machineId}:error`) : undefined,
  ]
    .filter(Boolean)
    .join(" ");
  const clearLabel =
    clear?.getAttribute("aria-label") || root.dataset.clearLabel || (clear ? nameText(clear) : "") || "Limpiar selección";
  const resultText = (count: number) => {
    if (count === 0) return emptyEl?.textContent?.trim() || "Sin resultados";
    const template = count === 1 ? (root.dataset.resultLabel ?? "1 resultado disponible") : (root.dataset.resultsLabel ?? "{count} resultados disponibles");
    return fromTemplate(template, { count: String(count) });
  };
  const removeText = (item: ComboboxItem) => fromTemplate(root.dataset.removeLabel ?? "Quitar {label}", { label: item.label });

  type Authored = {
    node: HTMLElement;
    item: ComboboxItem;
    key: string;
    text: HTMLElement | null;
    indicator: HTMLElement | null;
  };
  const authored: Authored[] = Array.from(root.querySelectorAll<HTMLElement>(selector.item)).map((node) => {
    const itemLabel = node.dataset.valueText ?? node.textContent?.trim() ?? "";
    return {
      node,
      item: {
        value: node.dataset.value ?? node.textContent?.trim() ?? "",
        label: itemLabel,
        description: node.dataset.description,
        disabled: node.hasAttribute("disabled") || node.getAttribute("aria-disabled") === "true" || node.hasAttribute("data-disabled"),
      } satisfies ComboboxItem,
      key: searchKey(itemLabel),
      text: node.querySelector<HTMLElement>(selector.itemText),
      indicator: node.querySelector<HTMLElement>(selector.itemIndicator),
    };
  });
  const makeCollection = (items: ComboboxItem[]) =>
    combobox.collection<ComboboxItem>({
      items,
      itemToString: (item) => item.label,
      itemToValue: (item) => item.value,
      isItemDisabled: (item) => Boolean(item.disabled),
    });

  // `$state.raw`: it is always REPLACED, never mutated element by element, so a deep proxy is not
  // needed.
  let visible = $state.raw(authored);
  const multiple = root.hasAttribute("data-multiple");

  const filterAuthoredItems = (value: string) => {
    const needle = searchKey(value.trim());
    const next = needle ? authored.filter((candidate) => candidate.key.includes(needle)) : authored;
    visible = next;
    const shown = new Set(next);
    for (const candidate of authored) {
      const hiddenNow = !shown.has(candidate);
      if (candidate.node.hidden !== hiddenNow) candidate.node.hidden = hiddenNow;
    }
  };

  const collection = $derived(makeCollection(visible.map(({ item }) => item)));

  const service = useMachine(combobox.machine, () => ({
    id: machineId,
    collection,
    name: input?.name || undefined,
    disabled: input?.disabled,
    invalid,
    readOnly: input?.readOnly,
    required: input?.required,
    multiple,
    openOnClick: !root.hasAttribute("data-open-on-input"),
    allowCustomValue: root.hasAttribute("data-allow-custom-value"),
    defaultValue: root.dataset.value?.split(" ").filter(Boolean),
    placeholder: input?.placeholder,
    // A search that was never resolved into a selection is still the user's work: `preserve` is the
    // only selectionBehavior that keeps it on blur/click-outside/Escape instead of reverting it.
    selectionBehavior: "preserve" as const,
    translations: { clearTriggerLabel: clearLabel },
    onInputValueChange(details: { reason?: string; inputValue: string }) {
      // Only what the user TYPED is a filter; any non-typed write (a selection's label, the empty
      // string after clear) resets to the full set.
      filterAuthoredItems(details.reason === "input-change" ? details.inputValue : "");
      root.dispatchEvent(new CustomEvent("sk-input-value-change", { bubbles: true, detail: { inputValue: details.inputValue } }));
    },
    onValueChange(details: { value: string[]; items: ComboboxItem[] }) {
      root.dispatchEvent(new CustomEvent("sk-value-change", { bubbles: true, detail: { value: details.value } }));
      // The other half of `selectionBehavior: "preserve"`. Single: the input shows what was chosen.
      // Multiple: the chip already shows it, so the query is spent.
      queueMicrotask(() => {
        const next = multiple ? "" : (details.items.at(-1)?.label ?? "");
        if (api.inputValue !== next) api.setInputValue(next, "script");
      });
    },
  }));

  const api = $derived(combobox.connect(service, normalizeProps));

  let selectedKey = "";
  const renderSelectedItems = () => {
    if (!selectedItemsEl) return;
    const nextKey = api.selectedItems.map(({ value }) => value).join(" ");
    selectedItemsEl.hidden = api.selectedItems.length === 0;
    if (nextKey === selectedKey) return;
    selectedKey = nextKey;
    selectedItemsEl.replaceChildren(
      ...api.selectedItems.map((item) => {
        const chip = document.createElement("span");
        chip.className = comboboxParts.selectedItem;
        chip.setAttribute("role", "listitem");
        const chipLabel = document.createElement("span");
        chipLabel.className = comboboxParts.selectedItemLabel;
        chipLabel.textContent = item.label;
        const remove = document.createElement("button");
        remove.className = `${comboboxParts.removeTrigger} sk-button sk-interactive`;
        remove.setAttribute("data-sk-combobox-remove-trigger", "");
        remove.setAttribute("data-icon-only", "");
        remove.setAttribute("data-size", "sm");
        remove.setAttribute("data-variant", "ghost");
        remove.dataset.value = item.value;
        remove.type = "button";
        remove.setAttribute("aria-label", removeText(item));
        const icon = document.createElement("span");
        icon.setAttribute("aria-hidden", "true");
        icon.textContent = "×";
        remove.append(icon);
        chip.append(chipLabel, remove);
        return chip;
      }),
    );
  };

  /*
   * ── Foco virtual ─────────────────────────────────────────────────────────────────────────────
   * DOM focus never leaves the input: `aria-activedescendant` points at the highlighted option.
   * Gated on which device moved the highlight last, so a focus ring does not chase the cursor.
   */
  let highlightSource: "keyboard" | "pointer" = "pointer";
  const applyHighlightSource = () => {
    if (!content) return;
    content.dataset.highlightSource = highlightSource;
    root.toggleAttribute("data-virtual-focus", highlightSource === "keyboard" && api.open && api.highlightedValue != null);
  };

  /*
   * Which rows this patch has to touch. A row's props are static except highlighted/selected, so
   * tracking just those two turns a full re-apply (194 rows, measured 31ms → 98ms across a filter
   * session with naive re-application) into patching the one row that lost the state and the one
   * that gained it.
   */
  let appliedHighlight: string | null = null;
  let appliedSelection = new Set<string>();
  let patchedOnce = false;
  const dirtyItems = (): Authored[] => {
    const selection = new Set(api.value);
    if (!patchedOnce) {
      patchedOnce = true;
      appliedHighlight = api.highlightedValue;
      appliedSelection = selection;
      return authored;
    }
    const dirty = new Set<string>();
    if (appliedHighlight !== api.highlightedValue) {
      if (appliedHighlight != null) dirty.add(appliedHighlight);
      if (api.highlightedValue != null) dirty.add(api.highlightedValue);
      appliedHighlight = api.highlightedValue;
    }
    for (const value of selection) if (!appliedSelection.has(value)) dirty.add(value);
    for (const value of appliedSelection) if (!selection.has(value)) dirty.add(value);
    appliedSelection = selection;
    if (dirty.size === 0) return [];
    return authored.filter((candidate) => dirty.has(candidate.item.value));
  };

  $effect(() => {
    if (!ready || !label || !control || !input || !trigger || !positioner || !content) return;
    applyZagProps(root, api.getRootProps() as DomProps);
    applyZagProps(label, api.getLabelProps() as DomProps);
    applyZagProps(control, api.getControlProps() as DomProps);
    if (input.readOnly) control.setAttribute("data-readonly", "");
    applyZagProps(input, api.getInputProps() as DomProps);
    if (describedBy) input.setAttribute("aria-describedby", describedBy);
    if (error) input.setAttribute("aria-errormessage", error.id);
    // Decorative only (see `combobox.ts`'s own note on `part: "trigger"`): no `getTriggerProps()`
    // spread, no click/focus wiring below. `data-state` alone drives the open/closed chevron swap.
    trigger.dataset.state = api.open ? "open" : "closed";
    if (clear) {
      applyZagProps(clear, api.getClearTriggerProps() as DomProps);
      clear.hidden = !(api.hasSelectedItems || input.value.length > 0);
      clear.tabIndex = 0;
    }
    const positionerProps = api.getPositionerProps() as DomProps;
    applyZagProps(positioner, anchorName ? (stripPositioningStyle(positionerProps) as DomProps) : positionerProps);
    if (anchorName) unbindAnchor = bindAnchor(control, positioner, anchorName);
    applyZagProps(content, api.getContentProps() as DomProps);
    if (emptyEl) emptyEl.hidden = visible.length > 0;
    const announcement = api.open ? resultText(visible.length) : "";
    if (statusEl && statusEl.textContent !== announcement) statusEl.textContent = announcement;
    renderSelectedItems();
    for (const candidate of dirtyItems()) {
      const itemProps = api.getItemProps({ item: candidate.item }) as DomProps;
      if (!multiple) itemProps["aria-selected"] = candidate.item.value === api.highlightedValue ? "true" : undefined;
      applyZagProps(candidate.node, itemProps);
      if (candidate.text) applyZagProps(candidate.text, api.getItemTextProps({ item: candidate.item }) as DomProps);
      if (candidate.indicator) applyZagProps(candidate.indicator, api.getItemIndicatorProps({ item: candidate.item }) as DomProps);
    }
    applyHighlightSource();
  });

  const cleanups: Array<() => void> = [];
  onMount(() => {
    if (!ready || !input || !trigger || !content) return;
    cleanups.push(bindZagEvents(input, () => api.getInputProps() as DomProps));
    if (clear) cleanups.push(bindZagEvents(clear, () => api.getClearTriggerProps() as DomProps));
    cleanups.push(bindZagEvents(content, () => api.getContentProps() as DomProps));
    for (const candidate of authored)
      cleanups.push(bindZagEvents(candidate.node, () => api.getItemProps({ item: candidate.item }) as DomProps));

    /*
     * The two triggers of the virtual focus. Capture and passive: nothing is touched, only observed.
     * A `pointermove` over an ALREADY highlighted item does not reach the machine (Zag cuts it off), so
     * the repaint cannot depend on the effect above.
     */
    const onKeyboardHighlight = (event: Event) => {
      if (!navigationKeys.has((event as KeyboardEvent).key)) return;
      highlightSource = "keyboard";
      applyHighlightSource();
    };
    const onPointerHighlight = () => {
      highlightSource = "pointer";
      applyHighlightSource();
    };
    root.addEventListener("keydown", onKeyboardHighlight, { capture: true, passive: true });
    content.addEventListener("pointermove", onPointerHighlight, { capture: true, passive: true });
    cleanups.push(
      () => root.removeEventListener("keydown", onKeyboardHighlight, true),
      () => content!.removeEventListener("pointermove", onPointerHighlight, true),
    );

    if (selectedItemsEl) {
      const items = selectedItemsEl;
      const onRemove = (event: MouseEvent) => {
        if (!(event.target instanceof Element)) return;
        const remove = event.target.closest<HTMLButtonElement>(selector.removeTrigger);
        if (!remove || !items.contains(remove)) return;
        const value = remove.dataset.value;
        if (!value) return;
        api.clearValue(value);
        api.focus();
      };
      items.addEventListener("click", onRemove);
      cleanups.push(() => items.removeEventListener("click", onRemove));
    }
  });
  onDestroy(() => {
    for (const cleanup of cleanups) cleanup();
    unbindAnchor?.();
  });
</script>

// packages/react/src/components/combobox.tsx
import { comboboxParts, type ComboboxItem } from "@skryensya/core/combobox";
import { formFieldParts } from "@skryensya/core/form-field";
import { combobox } from "@skryensya/core/machines";
import { normalizeProps, Portal, useMachine } from "@zag-js/react";
import { useId, useMemo, useState, type ReactNode, type RefObject } from "react";
import { useAnchored } from "./anchored.js";
import { Icon } from "./icon.js";
const cx = (...classes: Array<string | undefined>) =>
  classes.filter(Boolean).join(" ");
const combiningMarks = /\p{M}+/gu;
const searchKey = (value: string) =>
  value.normalize("NFD").replace(combiningMarks, "").toLocaleLowerCase();
type HighlightSource = "keyboard" | "pointer" | undefined;
// The keys that move the highlight inside the listbox (the same ones the machine handles).
const navigationKeys = new Set([
  "ArrowDown",
  "ArrowUp",
  "Home",
  "End",
  "PageUp",
  "PageDown",
]);
// The machine takes an array even when only one thing can be chosen. Authored markup carries a
// single `data-value`, so a lone string has to reach it as the one-element array it means.
const asValues = (value: string | readonly string[] | undefined) =>
  value === undefined ? undefined : typeof value === "string" ? [value] : [...value];
const defaultRemoveLabel = (item: ComboboxItem) => `Quitar ${item.label}`;
const defaultResultCountLabel = ({ count }: { count: number }) =>
  count === 1 ? "1 resultado disponible" : `${count} resultados disponibles`;

export type ComboboxProps = {
  /**
   * Where the positioned listbox is portalled. Absent it goes to the body, which is right in a page
   * and wrong in the gate: the listbox would land outside the box G2 measures, and the two bindings
   * would be compared with one of them missing its whole floating half.
   */
  container?: RefObject<HTMLElement>;
  id?: string;
  name?: string;
  label: ReactNode;
  hint?: ReactNode;
  error?: ReactNode;
  items: readonly ComboboxItem[];
  placeholder?: string;
  disabled?: boolean;
  readOnly?: boolean;
  required?: boolean;
  multiple?: boolean;
  value?: string | readonly string[];
  defaultValue?: string | readonly string[];
  inputValue?: string;
  defaultInputValue?: string;
  openOnClick?: boolean;
  allowCustomValue?: boolean;
  triggerIndicator?: ReactNode;
  itemIndicator?: ReactNode;
  clearIndicator?: ReactNode;
  removeIndicator?: ReactNode;
  clearLabel?: string;
  selectedLabel?: string;
  removeLabel?: (item: ComboboxItem) => string;
  emptyLabel?: ReactNode;
  resultCountLabel?: (details: { count: number; inputValue: string }) => string;
  onValueChange?: (details: { value: string[] }) => void;
  onInputValueChange?: (details: { inputValue: string }) => void;
};

export function Combobox({
  allowCustomValue,
  clearLabel = "Limpiar selección",
  clearIndicator,
  container,
  defaultInputValue = "",
  defaultValue,
  disabled,
  emptyLabel = "Sin resultados",
  error,
  hint,
  id,
  inputValue,
  itemIndicator,
  items,
  label,
  multiple,
  name,
  onInputValueChange,
  onValueChange,
  openOnClick = true,
  placeholder,
  readOnly,
  removeIndicator,
  removeLabel = defaultRemoveLabel,
  required,
  resultCountLabel = defaultResultCountLabel,
  selectedLabel = "Valores seleccionados",
  triggerIndicator,
  value,
}: ComboboxProps) {
  const generatedId = useId();
  const machineId = id ?? generatedId;
  const hintId = `${machineId}-hint`;
  const errorId = `${machineId}-error`;
  const [query, setQuery] = useState(defaultInputValue);
  /*
   * ── Virtual focus ────────────────────────────────────────────────────────────────────────────
   *
   * DOM focus never leaves the input: `aria-activedescendant` points at the highlighted option, so
   * nothing on screen says where the arrow keys have landed unless the option says it. It carries a
   * real focus ring, and while it does, the control drops its own; one ring at a time, so the ring
   * *moves* into the list and back out instead of stacking a box inside a box.
   *
   * Both attributes are gated on which device moved the highlight last, because the machine also
   * highlights on `pointermove` and a focus ring chasing the cursor reads as broken focus. Under the
   * pointer the hover tint carries the highlight alone. The updater returns the previous value when
   * nothing changed, so a mouse crossing the list does not re-render on every frame.
   */
  // Starts at `pointer`, matching the enhancer: at rest no key has moved the highlight, and only
  // `keyboard` changes what is drawn. Leaving it unset meant the two bindings disagreed about the
  // attribute before anyone had touched the control.
  const [highlightSource, setHighlightSource] = useState<HighlightSource>("pointer");
  const keepHighlightSource =
    (next: HighlightSource) => (previous: HighlightSource) =>
      previous === next ? previous : next;
  const effectiveQuery = inputValue ?? query;
  // Folded once per item list, not once per row per keystroke: `searchKey` normalizes to NFD and
  // strips combining marks, which is the most expensive thing in the filter and never changes.
  const searchKeys = useMemo(() => items.map(({ label }) => searchKey(label)), [items]);
  const allItems = useMemo(() => [...items], [items]);
  const filteredItems = useMemo(() => {
    const needle = searchKey(effectiveQuery.trim());
    if (!needle) return allItems;
    return items.filter((_, index) => searchKeys[index].includes(needle));
  }, [allItems, effectiveQuery, items, searchKeys]);
  const collection = useMemo(
    () =>
      combobox.collection<ComboboxItem>({
        items: filteredItems,
        itemToString: (item) => item.label,
        itemToValue: (item) => item.value,
        isItemDisabled: (item) => Boolean(item.disabled),
      }),
    [filteredItems],
  );
  const service = useMachine(combobox.machine, {
    id: machineId,
    collection,
    name,
    disabled,
    invalid: Boolean(error),
    readOnly,
    required,
    multiple,
    value: asValues(value),
    defaultValue: asValues(defaultValue),
    inputValue,
    defaultInputValue,
    openOnClick,
    allowCustomValue,
    placeholder,
    // A search that was never resolved into a selection is still the user's work: leaving the field
    // (blur, click outside, Escape) must not throw it away and leave them retyping. `preserve` is
    // the only selectionBehavior that keeps it, because the machine reverts the input on every one
    // of those exits. The cost is that CHOOSING no longer writes the label either, so `onValueChange`
    // below does that write itself: preserve on leave, replace on select (mirrors the vanilla layer).
    selectionBehavior: "preserve",
    translations: {
      clearTriggerLabel: clearLabel,
    },
    onInputValueChange(details) {
      // Only what the user TYPED is a filter. The machine writes this input too (the label after a
      // select, "" after clear), and filtering on that would leave the list showing the single row
      // you just picked the next time it opens. Any non-typed write resets to the full set.
      setQuery(details.reason === "input-change" ? details.inputValue : "");
      onInputValueChange?.({ inputValue: details.inputValue });
    },
    onValueChange(details) {
      onValueChange?.({ value: details.value });
      // The other half of `selectionBehavior: "preserve"`. Single: the input shows what was chosen.
      // Multiple: the chip already shows it, so the query is spent; clear it so the next search
      // starts from the whole list instead of the one match that produced this chip.
      queueMicrotask(() => {
        const next = multiple ? "" : (details.items.at(-1)?.label ?? "");
        if (api.inputValue !== next) api.setInputValue(next, "script");
      });
    },
  });
  const api = combobox.connect(service, normalizeProps);

  /* The anchor is the whole CONTROL, not the chevron button: the listbox lines up with the field the
   * user is typing into, and anchoring it to the chevron would pin it to a 32px square. */
  const anchor = useAnchored(machineId);
  const inputProps = api.getInputProps();
  const describedBy =
    [
      inputProps["aria-describedby"],
      hint ? hintId : undefined,
      error ? errorId : undefined,
    ]
      .filter(Boolean)
      .join(" ") || undefined;
  // Show the clear ✕ whenever there is something to clear (a chosen value OR text still in the
  // input), and hide it when the field is truly empty (mirrors the vanilla layer).
  const showClear = api.hasSelectedItems || api.inputValue.length > 0;

  return (
    <div
      {...api.getRootProps()}
      className={cx(formFieldParts.root, comboboxParts.root)}
      data-disabled={disabled ? "" : undefined}
      data-virtual-focus={
        highlightSource === "keyboard" && api.open && api.highlightedValue
          ? ""
          : undefined
      }
      onKeyDownCapture={(event) => {
        if (!navigationKeys.has(event.key)) return;
        setHighlightSource(keepHighlightSource("keyboard"));
      }}
    >
      <label
        {...api.getLabelProps()}
        className={cx(formFieldParts.label, comboboxParts.label)}
      >
        {label}
        {required ? (
          <span aria-hidden="true" className={formFieldParts.requiredIndicator}>
            *
          </span>
        ) : null}
      </label>
      {hint ? (
        <div className={formFieldParts.hint} id={hintId}>
          {hint}
        </div>
      ) : null}
      <div
        {...api.getControlProps()}
        {...anchor.anchor(comboboxParts.control)}
        data-readonly={readOnly ? "" : undefined}
      >
        <div className={comboboxParts.value}>
          {multiple && api.selectedItems.length ? (
            <div
              aria-label={selectedLabel}
              className={comboboxParts.selectedItems}
              role="list"
            >
              {api.selectedItems.map((item) => (
                <span
                  className={comboboxParts.selectedItem}
                  key={item.value}
                  role="listitem"
                >
                  <span className={comboboxParts.selectedItemLabel}>
                    {item.label}
                  </span>
                  <button
                    aria-label={removeLabel(item)}
                    className={cx(
                      comboboxParts.removeTrigger,
                      "sk-button",
                      "sk-interactive",
                    )}
                    data-icon-only=""
                    data-size="sm"
                    data-variant="ghost"
                    onClick={() => {
                      api.clearValue(item.value);
                      api.focus();
                    }}
                    type="button"
                  >
                    {removeIndicator ?? <Icon name="close" size="sm" />}
                  </button>
                </span>
              ))}
            </div>
          ) : null}
          <input
            {...inputProps}
            aria-describedby={describedBy}
            aria-errormessage={error ? errorId : undefined}
            className={comboboxParts.input}
          />
        </div>
        {/* Rendered-and-hidden rather than conditional, which is what the enhancer can do with
            authored markup and therefore what the contract's template says. `hidden` keeps it out
            of the accessibility tree exactly as absence would, and it is what the CSS styles. */}
        <button
          {...api.getClearTriggerProps()}
          className={cx(comboboxParts.clear, "sk-button", "sk-interactive")}
          data-icon-only=""
          data-size="sm"
          data-variant="ghost"
          hidden={!showClear}
          tabIndex={0}
          type="button"
        >
          {clearIndicator ?? <Icon name="close" size="sm" />}
        </button>
        {/*
          Decorative, not a second control: Zag's own `getTriggerProps()` already defaults this to
          `tabIndex: -1` (never a Tab stop), and every open path here - typing, `openOnClick` on
          the input itself - never went through it either. What made it read as an independent
          button was purely visual (its own `.sk-button` ghost hover/pressed feedback on a mouse
          click Zag still wired up), not a real second interaction surface. `aria-hidden` and a
          plain `span` remove that affordance instead of just restyling it; the input's own
          `role="combobox"` + `aria-expanded` already say everything a screen reader needs.
        */}
        <span aria-hidden="true" className={comboboxParts.trigger} data-state={api.open ? "open" : "closed"}>
          {triggerIndicator ?? (
            <>
              <span data-state="closed">
                <Icon name="chevron-down" size="md" />
              </span>
              <span data-state="open">
                <Icon name="chevron-up" size="md" />
              </span>
            </>
          )}
        </span>
      </div>
      {error ? (
        <div className={formFieldParts.error} id={errorId}>
          {error}
        </div>
      ) : null}
      <div
        aria-atomic="true"
        className={cx(comboboxParts.status, "sk-visually-hidden")}
        role="status"
      >
        {api.open
          ? resultCountLabel({
              count: filteredItems.length,
              inputValue: api.inputValue,
            })
          : null}
      </div>
      <Portal container={container}>
        <div {...anchor.positioner(api.getPositionerProps(), comboboxParts.positioner)}>
          <div
            {...api.getContentProps()}
            className={cx(comboboxParts.content, "sk-scrollbar")}
            data-highlight-source={highlightSource}
            onPointerMove={() => setHighlightSource(keepHighlightSource("pointer"))}
          >
            {filteredItems.map((item) => (
              <div
                {...api.getItemProps({ item })}
                /*
                 * Zag's `aria-selected` tracks the COMMITTED value, not the row under
                 * `aria-activedescendant`. The WAI reference implementation
                 * (`combobox-autocomplete.js`, `setCurrentOptionStyle`) does the opposite for
                 * single-select: it moves `aria-selected="true"` onto whichever option is highlighted
                 * as you arrow through the list, before Enter commits anything. That is what
                 * "visually indicated as the currently selected value" means in the APG's
                 * roles/states table. Multiple stays on Zag's default: with chips, `aria-selected`
                 * genuinely means "part of the chosen set" (aria-multiselectable="true"), a state the
                 * base combobox pattern does not cover. Placed after the spread so it wins.
                 */
                aria-selected={
                  multiple
                    ? api.getItemState({ item }).selected
                      ? "true"
                      : undefined
                    : item.value === api.highlightedValue
                      ? "true"
                      : undefined
                }
                className={`${comboboxParts.item} sk-interactive`}
                /* What the enhancer reads to build its collection: a row's `textContent` is label +
                   description + indicator glued together, which is not the label. Written here too
                   so the two bindings land on the same row. */
                data-description={item.description}
                data-value-text={item.label}
                key={item.value}
              >
                <span className={comboboxParts.itemCopy}>
                  <span
                    {...api.getItemTextProps({ item })}
                    className={comboboxParts.itemLabel}
                  >
                    {item.label}
                  </span>
                  {item.description ? (
                    <span className={comboboxParts.itemDescription}>
                      {item.description}
                    </span>
                  ) : null}
                </span>
                <span
                  {...api.getItemIndicatorProps({ item })}
                  className={comboboxParts.itemIndicator}
                >
                  {itemIndicator ?? "✓"}
                </span>
              </div>
            ))}
            {/* Same rendered-and-hidden rule as the clear control above. */}
            <div
              className={comboboxParts.empty}
              hidden={filteredItems.length > 0}
              role="presentation"
            >
              {emptyLabel}
            </div>
          </div>
        </div>
      </Portal>
    </div>
  );
}
