// packages/vanilla/src/components/DatePicker.svelte
<script lang="ts">
  import {
    anchoredParts,
    anchorNameFor,
    bindAnchor,
    stripPositioningStyle,
    supportsAnchorPositioning,
  } from "@skryensya/core/anchored";
  import { datePicker } from "@skryensya/core/machines";
  import {
    defaultDayLabel,
    defaultNextTriggerLabel,
    defaultPrevTriggerLabel,
    defaultViewTriggerLabel,
    parseCalendarDate,
    unusedIntlTranslations,
  } from "@skryensya/core/calendar";
  import { datePickerContract, datePickerEvents, datePickerParts, defaultContentLabel, defaultTriggerLabel } from "@skryensya/core/date-picker";
  import { calendarParts } from "@skryensya/core/calendar";
  import { normalizeProps, useMachine } from "@zag-js/svelte";
  import { onDestroy, onMount } from "svelte";
  import { bindParts, type PartBinding } from "../runtime/bind-part.svelte";
  import { getRoot, uniqueId } from "../runtime/svelte-hydrate";
  import { remountIcons } from "../icon.js";
  import CalendarView from "./CalendarView.svelte";

  /*
   * DATE PICKER, a machine-backed enhancer over `@zag-js/date-picker` (the SAME machine React uses).
   *
   * It splits the work by owner, like Carousel: the CONTROL (label, input, trigger, clear) is authored
   * markup that gets patched; the CALENDAR is chrome derived from the state and owned by `CalendarView`
   * (shared with the standalone Calendar), and this component only puts the popover around it.
   *
   * The native `type="date"` input is still the no-JS layer: it shares `.sk-date-picker__control`, so
   * the native version and the enhanced one look like the SAME field, and without the vanilla layer
   * mounted the consumer authors the native one. This enhancer only appears when the markup asks for
   * `data-sk-date-picker`.
   */
  const root = getRoot();

  const label = root.querySelector<HTMLElement>(`.${datePickerParts.label}`);
  const control = root.querySelector<HTMLElement>(`.${datePickerParts.control}`);
  const input = root.querySelector<HTMLInputElement>(`.${datePickerParts.input}`);
  const trigger = root.querySelector<HTMLButtonElement>(`.${datePickerParts.trigger}`);
  const clear = root.querySelector<HTMLButtonElement>(`.${datePickerParts.clear}`);
  const authoredPlaceholder = input?.getAttribute("placeholder") ?? null;
  const authoredClearLabel = clear?.getAttribute("aria-label") ?? null;

  if (!control) throw new Error(`[data-sk-date-picker] necesita un .${datePickerParts.control}.`);
  if (!input) throw new Error(`[data-sk-date-picker] necesita un .${datePickerParts.input}.`);
  if (!trigger) throw new Error(`[data-sk-date-picker] necesita un .${datePickerParts.trigger}.`);

  if (!root.id) root.id = uniqueId("sk-date-picker");
  const locale = root.dataset.locale || datePickerContract.options.locale.default;

  /* The positioner is rendered by this component (it is derived chrome), so the reference comes from the
   * template below and not from a query over authored markup, like the control does. */
  let positioner: HTMLElement | undefined = $state();

  const service = useMachine(datePicker.machine, () => ({
    id: root.id,
    name: root.dataset.name || input.name || undefined,
    // Explicit date, never an ambiguous locale string: locale and time zone are authored or fall back to es/UTC.
    locale,
    timeZone: root.dataset.timeZone || "UTC",
    selectionMode: (root.dataset.selectionMode === "range" ? "range" : "single") as "single" | "range",
    /* The initial date and the allowed range. All three were missing: the authored markup had no way to
     * state any of them, while the React binding accepted props this half discarded. */
    defaultValue: root.dataset.value?.split(" ").filter(Boolean).map((date) => parseCalendarDate(date)!),
    min: parseCalendarDate(root.dataset.min),
    max: parseCalendarDate(root.dataset.max),
    disabled: root.hasAttribute("data-disabled"),
    readOnly: root.hasAttribute("data-readonly"),
    required: root.hasAttribute("data-required"),
    invalid: root.hasAttribute("data-invalid"),
    // Stable calendar height across months: always six rows, so opening does not reflow the page.
    fixedWeeks: true,
    /*
     * Zag's own `defaultTranslations` is English only, with no language condition. A date picker in
     * Spanish announced "Choose 15 de agosto" in English, the same gap that was fixed in the React binding.
     */
    translations: {
      ...unusedIntlTranslations(),
      trigger: defaultTriggerLabel(locale),
      content: defaultContentLabel(locale),
      dayCell: defaultDayLabel(locale),
      viewTrigger: defaultViewTriggerLabel(locale),
      prevTrigger: defaultPrevTriggerLabel(locale),
      nextTrigger: defaultNextTriggerLabel(locale),
    },
    onValueChange(details: { valueAsString: string[] }) {
      root.dispatchEvent(
        new CustomEvent(datePickerEvents.valueChange, { bubbles: true, detail: { value: details.valueAsString } }),
      );
    },
  }));

  const api = $derived(datePicker.connect(service, normalizeProps));

  /*
   * Anchor positioning, now via the Anchoring pattern (ADR-25). Where the browser has the API it places
   * the calendar itself and we do NOT pass Zag the inline `style`, so two engines do not fight. Without
   * the API, Zag's `style` passes through untouched and it positions (the fallback).
   *
   * This used to stamp `--sk-date-picker-anchor` on the root and date-picker.css read it on the
   * positioner, but NOTHING ever put an `anchor-name` on the control: half the wiring was missing, so
   * the `@supports` block placed nothing and Zag ended up positioning every time.
   */
  const anchored = supportsAnchorPositioning();
  let unbindAnchor: (() => void) | undefined;
  /** Generic, so the template spread below needs no cast either: `stripPositioningStyle` takes any object. */
  const positionerProps = <T extends object>(props: T) => (anchored ? stripPositioningStyle(props) : props);

  /*
   * The calendar's own triggers (prev/next/view/day) are rendered by CalendarView with their handlers
   * already wired by Svelte, so only the authored control appears here.
   */
  const bindings: PartBinding[] = [
    { part: "root", node: () => root, props: () => api.getRootProps() },
    { part: "label", node: () => label, props: () => api.getLabelProps() },
    {
      part: "control",
      node: () => control,
      props: () => api.getControlProps(),
      classes: [anchoredParts.anchor],
    },
    {
      part: "input",
      node: () => input,
      props: () => api.getInputProps({ index: 0 }),
      events: true,
      after: () => {
        if (authoredPlaceholder !== null) input.placeholder = authoredPlaceholder;
      },
    },
    { part: "trigger", node: () => trigger, props: () => api.getTriggerProps(), events: true },
    {
      part: "clearTrigger",
      node: () => clear,
      props: () => api.getClearTriggerProps(),
      events: true,
      after: (node) => {
        if (authoredClearLabel !== null) node.setAttribute("aria-label", authoredClearLabel);
        // Clear only makes sense with a date set; with no value it takes up no room in the field.
        node.hidden = api.value.length === 0;
      },
    },
  ];

  bindParts(bindings);

  onMount(() => {
    // The anchor-to-popup wiring, after the first render: the positioner comes from the template below.
    if (anchored) unbindAnchor = bindAnchor(control, positioner, anchorNameFor(root.id));
    // The chevrons are authored as `data-sk-icon` placeholders and hydrated by the already-registered set.
    remountIcons(root);
  });
  onDestroy(() => unbindAnchor?.());
</script>

<div
  bind:this={positioner}
  {...positionerProps(api.getPositionerProps())}
  class="{datePickerParts.positioner} {anchoredParts.positioner}"
>
  <div {...api.getContentProps()} class="{datePickerParts.content} {calendarParts.root}">
    <CalendarView {api} {locale} />
  </div>
</div>

// packages/react/src/components/date-picker.tsx
import {
  datePickerContract,
  datePickerParts,
  defaultContentLabel,
  defaultTriggerLabel,
} from "@skryensya/core/date-picker";
import type { SignatureOptionsOf } from "@skryensya/core/contract";
import {
  calendarParts,
  defaultDayLabel,
  defaultNextTriggerLabel,
  defaultPrevTriggerLabel,
  defaultViewTriggerLabel,
  unusedIntlTranslations,
} from "@skryensya/core/calendar";
import type { DateValue, DateView, DayTableCellState } from "@skryensya/core/calendar";
import { datePicker } from "@skryensya/core/machines";
import { normalizeProps, Portal, useMachine } from "@zag-js/react";
import { useId, type ReactNode, type RefObject } from "react";
import { useAnchored } from "./anchored.js";
import { asDate, asDates, CalendarBody } from "./calendar.js";
import { Icon } from "./icon.js";

// `selectionMode` comes from the contract, so Core stays the only place its values are defined.
export type DatePickerProps = Pick<
  SignatureOptionsOf<typeof datePickerContract, "DatePicker">,
  "selectionMode"
> & {
  /** Where the popover is portalled. Absent it goes to the body: see `ComboboxProps.container`. */
  container?: RefObject<HTMLElement>;
  id?: string;
  name?: string;
  label?: ReactNode;
  locale?: string;
  timeZone?: string;
  /* Dates as `DateValue` OR as the ISO strings authored markup carries: see `CalendarProps`. */
  value?: readonly (DateValue | string)[] | string;
  defaultValue?: readonly (DateValue | string)[] | string;
  min?: DateValue | string;
  max?: DateValue | string;
  disabled?: boolean;
  readOnly?: boolean;
  required?: boolean;
  invalid?: boolean;
  placeholder?: string;
  triggerIcon?: ReactNode;
  previousIcon?: ReactNode;
  nextIcon?: ReactNode;
  clearLabel?: string;
  /** Accessible name for the calendar-icon trigger, by open state. Default is locale-aware. */
  triggerLabel?: (open: boolean) => string;
  /** Accessible name for the popover holding the calendar. Default is locale-aware. */
  contentLabel?: string;
  /** Accessible name for a day cell, by state. Default is locale-aware. */
  dayLabel?: (state: DayTableCellState) => string;
  /** Accessible name for the day/month/year view-switch button. */
  viewTriggerLabel?: (view: DateView) => string;
  /** Accessible name for "go back". Previous month/year/decade depending on the open view. */
  prevTriggerLabel?: (view: DateView) => string;
  /** Accessible name for "go forward". Next month/year/decade depending on the open view. */
  nextTriggerLabel?: (view: DateView) => string;
  onValueChange?: (details: { value: string[] }) => void;
};

/*
 * DATE PICKER: the editable field (label, input, trigger, clear) plus a popover. The calendar
 * chrome inside the popover is `CalendarBody`, the same component `Calendar` (./calendar.tsx)
 * renders standalone: DatePicker never re-implements the grid, it only supplies the machine
 * instance (popover-mode, not inline) and the field around it.
 */
export function DatePicker({
  clearLabel = "Limpiar",
  container,
  contentLabel,
  dayLabel,
  defaultValue,
  disabled,
  id,
  invalid,
  label,
  locale = "es",
  max,
  min,
  name,
  nextIcon,
  nextTriggerLabel,
  onValueChange,
  placeholder,
  prevTriggerLabel,
  previousIcon,
  readOnly,
  required,
  selectionMode = "single",
  timeZone = "UTC",
  triggerIcon,
  triggerLabel,
  value,
  viewTriggerLabel,
}: DatePickerProps) {
  const generatedId = useId();
  const service = useMachine(datePicker.machine, {
    id: id ?? generatedId,
    name,
    locale,
    timeZone,
    selectionMode,
    value: asDates(value),
    defaultValue: asDates(defaultValue),
    min: asDate(min),
    max: asDate(max),
    disabled,
    readOnly,
    required,
    invalid,
    fixedWeeks: true,
    translations: {
      ...unusedIntlTranslations(),
      trigger: triggerLabel ?? defaultTriggerLabel(locale),
      content: contentLabel ?? defaultContentLabel(locale),
      dayCell: dayLabel ?? defaultDayLabel(locale),
      viewTrigger: viewTriggerLabel ?? defaultViewTriggerLabel(locale),
      prevTrigger: prevTriggerLabel ?? defaultPrevTriggerLabel(locale),
      nextTrigger: nextTriggerLabel ?? defaultNextTriggerLabel(locale),
    },
    onValueChange(details) {
      onValueChange?.({ value: details.valueAsString });
    },
  });
  const api = datePicker.connect(service, normalizeProps);

  /* The anchor is the whole control (input + buttons), not the calendar button: the panel lines up with
   * the field, which is what the calendar is editing. */
  const anchor = useAnchored(id ?? generatedId);
  const inputCount = selectionMode === "range" ? 2 : 1;

  return (
    <div
      {...api.getRootProps()}
      className={datePickerParts.root}
      data-selection-mode={selectionMode}
    >
      {label ? (
        <label {...api.getLabelProps()} className={datePickerParts.label}>
          {label}
        </label>
      ) : null}
      <div {...api.getControlProps()} {...anchor.anchor(datePickerParts.control)}>
        {Array.from({ length: inputCount }, (_, index) => (
          <input
            {...api.getInputProps({ index })}
            className={datePickerParts.input}
            key={index}
            placeholder={placeholder}
          />
        ))}
        {/* Rendered-and-hidden, not conditional: the enhancer patches authored markup and can only
            toggle `hidden`, so that is what the contract's template can say. */}
        <button
          {...api.getClearTriggerProps()}
          aria-label={clearLabel}
          className={`${datePickerParts.clear} sk-button sk-interactive`}
          data-icon-only=""
          data-size="sm"
          data-variant="ghost"
          hidden={api.value.length === 0}
          type="button"
        >
          <Icon name="close" size="sm" />
        </button>
        <button
          {...api.getTriggerProps()}
          className={`${datePickerParts.trigger} sk-button sk-interactive`}
          data-icon-only=""
          data-size="sm"
          data-variant="ghost"
          type="button"
        >
          {triggerIcon ?? <Icon name="calendar" size="sm" />}
        </button>
      </div>
      <Portal container={container}>
        <div {...anchor.positioner(api.getPositionerProps(), datePickerParts.positioner)}>
          <div
            {...api.getContentProps()}
            className={`${datePickerParts.content} ${calendarParts.root}`}
          >
            <CalendarBody
              api={api}
              locale={locale}
              nextIcon={nextIcon}
              previousIcon={previousIcon}
            />
          </div>
        </div>
      </Portal>
    </div>
  );
}

export type NativeDatePickerProps = {
  label: ReactNode;
  name?: string;
  locale?: string;
  id?: string;
};

/*
 * THE NATIVE DATE FIELD: the layer that works with no script at all.
 *
 * A real `<input type="date">` inside the same field chrome, so the enhanced control and this one
 * read as the SAME field rather than two designs. The browser owns the picker, the keyboard, the
 * locale format and the form; the system contributes the label wiring and the box around it.
 *
 * Its own signature rather than an option on `DatePicker`, for the reason `Select.native` is one:
 * choosing between them is choosing who owns the behaviour, and no flag should be able to stand in
 * for that decision.
 */
export function NativeDatePicker({ id, label, locale, name }: NativeDatePickerProps) {
  const generatedId = useId();
  const inputId = id ?? generatedId;

  return (
    <div className={datePickerParts.root}>
      {/* Named through `aria-labelledby` rather than `for`/`id`: see the contract, where the
          reason is the shared stage rather than the markup. */}
      <label className={datePickerParts.label} id={`${inputId}-label`}>
        {label}
      </label>
      <div className={datePickerParts.control}>
        <input
          aria-labelledby={`${inputId}-label`}
          className={datePickerParts.input}
          lang={locale}
          name={name}
          type="date"
        />
      </div>
    </div>
  );
}
