// packages/vanilla/src/components/NumberField.svelte
<script lang="ts">
  import { numberInput } from "@skryensya/core/machines";
  import {
    numberFieldContract,
    numberFieldEvents,
    numberFieldFormatOptions,
    numberFieldParts,
  } from "@skryensya/core/number-field";
  import { normalizeProps, useMachine } from "@zag-js/svelte";
  import { bindParts, type PartBinding } from "../runtime/bind-part.svelte";
  import { getRoot, uniqueId } from "../runtime/svelte-hydrate";

  /*
   * NUMBER FIELD, a machine-backed enhancer over `@zag-js/number-input` (the SAME machine React uses,
   * via `@skryensya/core/machines`). It renders no structure: it scans its authored markup and patches
   * the attributes `connect` returns onto those nodes.
   */
  const root = getRoot();

  const label = root.querySelector<HTMLElement>("[data-sk-number-field-label]");
  const control = root.querySelector<HTMLElement>("[data-sk-number-field-control]");
  const input = root.querySelector<HTMLInputElement>("[data-sk-number-field-input]");
  const decrement = root.querySelector<HTMLButtonElement>("[data-sk-number-field-decrement]");
  const increment = root.querySelector<HTMLButtonElement>("[data-sk-number-field-increment]");
  /* The authored hint, tied to the input the way React ties it: the machine's own input props carry
     no description, so a hint beside the field was never read with it. */
  const hint = root.querySelector<HTMLElement>(`.${numberFieldParts.hint}`);

  // Captured ONCE, never re-read from the DOM: `getRootProps().id` returns a namespaced id that
  // `applyZagProps` writes back onto `root.id`. Reading it live from `useMachine`'s reactive factory
  // would feed that prefix back on every recomputation.
  const machineId = root.id || uniqueId("sk-number-field");
  if (hint && !hint.id) hint.id = `${machineId}-hint`;
  const authoredDescribedBy = input?.getAttribute("aria-describedby") ?? undefined;
  const describedBy = [authoredDescribedBy, hint?.id].filter(Boolean).join(" ") || undefined;

  const numberOf = (value: string | undefined) => (!value ? undefined : Number(value));

  const service = useMachine(numberInput.machine, () => ({
    id: machineId,
    name: input?.name || undefined,
    locale: root.lang || document.documentElement.lang || numberFieldContract.options.locale.default,
    defaultValue: input?.defaultValue,
    formatOptions: numberFieldFormatOptions,
    min: numberOf(input?.min),
    max: numberOf(input?.max),
    step: numberOf(input?.step),
    disabled: input?.disabled,
    readOnly: input?.readOnly,
    required: input?.required,
    invalid: root.hasAttribute("data-invalid"),
    translations: {
      decrementLabel: decrement?.getAttribute("aria-label") ?? numberFieldContract.options.decrementLabel.default,
      incrementLabel: increment?.getAttribute("aria-label") ?? numberFieldContract.options.incrementLabel.default,
    },
    onValueChange(details: { value: string; valueAsNumber: number }) {
      root.dispatchEvent(
        new CustomEvent(numberFieldEvents.valueChange, {
          bubbles: true,
          detail: { value: details.value, valueAsNumber: details.valueAsNumber },
        }),
      );
    },
  }));

  const api = $derived(numberInput.connect(service, normalizeProps));

  /*
   * Incomplete markup: the enhancer stays silent, like the imperative connector it replaces (it never
   * breaks the page over a badly authored root).
   *
   * ONE PREDICATE, READ BY BOTH HOOKS. It used to be written twice and the two disagreed: the patch
   * required all five parts, the event wiring required only the three interactive ones. A root with
   * an input and both buttons but no `[data-sk-number-field-label]` therefore got LIVE LISTENERS AND
   * ZERO ATTRIBUTES - pressing increment ran the machine and nothing was ever written back to the
   * DOM. Silent in the way that matters least: the component looked authored and behaved dead.
   */
  const parts =
    label && control && input && decrement && increment
      ? { label, control, input, decrement, increment }
      : null;

  const bindings: PartBinding[] = [
    // Every `node()` is gated on the same `parts`, which is what keeps the all-or-nothing rule: an
    // incomplete root binds nothing at all, not even its own attributes.
    { part: "root", node: () => (parts ? root : null), props: () => api.getRootProps() },
    { part: "label", node: () => parts?.label, props: () => api.getLabelProps() },
    { part: "control", node: () => parts?.control, props: () => api.getControlProps() },
    {
      part: "input",
      node: () => parts?.input,
      props: () => ({ ...api.getInputProps(), "aria-describedby": describedBy }),
      events: true,
    },
    {
      part: "decrement",
      node: () => parts?.decrement,
      props: () => api.getDecrementTriggerProps(),
      events: true,
    },
    {
      part: "increment",
      node: () => parts?.increment,
      props: () => api.getIncrementTriggerProps(),
      events: true,
    },
  ];

  bindParts(bindings);
</script>

// packages/react/src/components/number-field.tsx
import {
  numberFieldEvents,
  numberFieldParts,
  numberFieldContract,
} from "@skryensya/core/number-field";
import { numberInput } from "@skryensya/core/machines";
import { normalizeProps, useMachine } from "@zag-js/react";
import { useId, useRef, type ReactNode } from "react";
import { Icon } from "./icon.js";

/* Derived, never restated: the defaults live in the contract. */
const {
  decrementLabel: decrementLabelOption,
  incrementLabel: incrementLabelOption,
  locale: localeOption,
} = numberFieldContract.options;

export type NumberFieldProps = {
  id?: string;
  name?: string;
  /** Names the field. Contract slot is text-only. */
  label: string;
  /** Optional supporting text under the control. Contract slot is text-only. */
  hint?: string;
  value?: string;
  defaultValue?: string;
  min?: number;
  max?: number;
  step?: number;
  disabled?: boolean;
  readOnly?: boolean;
  required?: boolean;
  invalid?: boolean;
  locale?: string;
  formatOptions?: Intl.NumberFormatOptions;
  decrementLabel?: string;
  incrementLabel?: string;
  decrementIcon?: ReactNode;
  incrementIcon?: ReactNode;
  onValueChange?: (details: { value: string; valueAsNumber: number }) => void;
};

export function NumberField({
  decrementIcon,
  decrementLabel = decrementLabelOption.default,
  defaultValue,
  disabled,
  formatOptions,
  hint,
  id,
  incrementIcon,
  incrementLabel = incrementLabelOption.default,
  invalid,
  label,
  locale = localeOption.default,
  max,
  min,
  name,
  onValueChange,
  readOnly,
  required,
  step,
  value,
}: NumberFieldProps) {
  const generatedId = useId();
  const resolvedId = id ?? generatedId;
  const rootRef = useRef<HTMLDivElement>(null);
  const hintId = hint ? `${resolvedId}-hint` : undefined;
  const service = useMachine(numberInput.machine, {
    id: resolvedId,
    name,
    locale,
    value,
    defaultValue,
    min,
    max,
    step,
    disabled,
    readOnly,
    required,
    invalid,
    formatOptions,
    translations: { decrementLabel, incrementLabel },
    onValueChange(details) {
      onValueChange?.(details);
      rootRef.current?.dispatchEvent(
        new CustomEvent(numberFieldEvents.valueChange, {
          bubbles: true,
          detail: { value: details.value, valueAsNumber: details.valueAsNumber },
        }),
      );
    },
  });
  const api = numberInput.connect(service, normalizeProps);
  const inputProps = api.getInputProps();
  const describedBy = [inputProps["aria-describedby"], hintId].filter(Boolean).join(" ") || undefined;
  return (
    <div
      {...api.getRootProps()}
      className={numberFieldParts.root}
      data-invalid={invalid || undefined}
      data-sk-number-field=""
      ref={rootRef}
    >
      <label {...api.getLabelProps()} className={numberFieldParts.label}>
        {label}
      </label>
      <div {...api.getControlProps()} className={numberFieldParts.control}>
        {/* Composed icon buttons: the button provides the shape and the state layer, the accessible
            name is written by Zag (`translations`), and the glyph stays decorative. */}
        <button
          {...api.getDecrementTriggerProps()}
          className={`sk-button sk-interactive ${numberFieldParts.decrement}`}
          data-icon-only=""
          data-size="sm"
          data-variant="ghost"
          type="button"
        >
          {decrementIcon ?? <Icon name="remove" size="sm" />}
        </button>
        <input {...inputProps} aria-describedby={describedBy} className={numberFieldParts.input} />
        <button
          {...api.getIncrementTriggerProps()}
          className={`sk-button sk-interactive ${numberFieldParts.increment}`}
          data-icon-only=""
          data-size="sm"
          data-variant="ghost"
          type="button"
        >
          {incrementIcon ?? <Icon name="add" size="sm" />}
        </button>
      </div>
      {hint ? (
        <span className={numberFieldParts.hint} id={hintId}>
          {hint}
        </span>
      ) : null}
    </div>
  );
}
