// packages/vanilla/src/components/TagsInput.svelte
<script lang="ts">
  import { tagsInput } from "@skryensya/core/machines";
  import { tagParts } from "@skryensya/core/tag";
  import { tagsInputAttrs, tagsInputContract, tagsInputEvents, tagsInputParts } from "@skryensya/core/tags-input";
  import { normalizeProps, useMachine } from "@zag-js/svelte";
  import { onMount } from "svelte";
  import { remountIcons } from "../icon.js";
  import { bindParts, type PartBinding } from "../runtime/bind-part.svelte";
  import { getRoot, uniqueId } from "../runtime/svelte-hydrate";

  /*
   * TAGS INPUT, a machine-backed enhancer over `@zag-js/tags-input`: the SAME machine the React
   * binding drives, through `@skryensya/core/machines`.
   *
   * IT RENDERS THE TAGS, and that is the deliberate exception this component shares with
   * FileUpload. The rule it bends ("an enhancer renders nothing") is about AUTHORED STRUCTURE:
   * markup a person wrote, which an enhancer has no business replacing. The tags are not that. They
   * are the VALUE, written into the markup so the field is readable before its JavaScript arrives,
   * and the moment somebody types one there is no authored element for it to be. Patching alone
   * would give the vanilla binding a field that can delete tags and never add one.
   *
   * So the authored list is read for its values, and then replaced, once, by the live one: the
   * `items` node exists in the contract for exactly this, and `replaceWith` is what hands the seed
   * over to the machine in a single operation instead of emptying a node and filling it again.
   */
  const root = getRoot();

  const control = root.querySelector<HTMLElement>(`[${tagsInputAttrs.control}]`);
  const authoredList = root.querySelector<HTMLElement>(`[${tagsInputAttrs.list}]`);
  const input = root.querySelector<HTMLInputElement>(`[${tagsInputAttrs.input}]`);
  const hidden = root.querySelector<HTMLInputElement>(`[${tagsInputAttrs.hidden}]`);

  /* The live list, swapped in for the authored one below. */
  let renderedList = $state<HTMLElement | null>(null);

  /* Captured once, before any patch can rewrite them. Same reason Rating captures its own id. */
  const machineId = root.id || uniqueId("sk-tags-input");
  const authoredLabel = input?.getAttribute("aria-label") ?? undefined;

  /* The seed: the tags the author wrote, in the order they wrote them. */
  const defaultValue = Array.from(
    authoredList?.querySelectorAll<HTMLElement>(`[${tagsInputAttrs.item}]`) ?? [],
  )
    .map((item) => item.dataset.value ?? "")
    .filter((value) => value !== "");

  const removeLabel =
    root.querySelector<HTMLElement>(`[${tagsInputAttrs.remove}]`)?.getAttribute("aria-label") ??
    tagsInputContract.options.removeLabel.default;

  const numberOf = (value: string | null) => (value === null || value === "" ? undefined : Number(value));

  const service = useMachine(tagsInput.machine, () => ({
    id: machineId,
    name: root.getAttribute("data-name") ?? undefined,
    /*
     * SPREAD, NOT `defaultValue: undefined`. `@zag-js/core`'s `bindable` decides controlled from the
     * presence of the KEY, not from the value being defined. The React binding carries the same
     * note, and it was measured against the machine rather than guessed.
     */
    ...(defaultValue.length === 0 ? {} : { defaultValue }),
    ...(numberOf(root.getAttribute("data-max")) === undefined
      ? {}
      : { max: numberOf(root.getAttribute("data-max")) }),
    delimiter: root.getAttribute("data-delimiter") ?? tagsInputContract.options.delimiter.default,
    allowDuplicates: root.hasAttribute("data-allow-duplicates"),
    /* The only option whose attribute means the NEGATIVE: `editable` is on unless it says otherwise. */
    editable: root.getAttribute("data-editable") !== "false",
    disabled: root.hasAttribute("data-disabled"),
    readOnly: root.hasAttribute("data-readonly"),
    invalid: root.hasAttribute("data-invalid"),
    required: root.hasAttribute("data-required"),
    onValueChange(details: { value: string[] }) {
      root.dispatchEvent(
        new CustomEvent(tagsInputEvents.valueChange, { bubbles: true, detail: { value: details.value } }),
      );
    },
  }));

  const api = $derived(tagsInput.connect(service, normalizeProps));

  /*
   * THE HAND-OVER, once. After it the authored seed is gone and the machine owns the list; doing it
   * on mount rather than in an effect keeps it from running again on every state change.
   */
  onMount(() => {
    if (authoredList && renderedList) authoredList.replaceWith(renderedList);
  });

  /* The rendered rows carry `data-sk-icon` placeholders; the page's own icon set upgrades them. */
  $effect(() => {
    void api.value.length;
    remountIcons(root);
  });

  /* All or nothing, the rule NumberField's comment spells out: an incomplete root binds nothing. */
  const parts = control && input && hidden ? { control, input, hidden } : null;

  const bindings: PartBinding[] = [
    { part: "root", node: () => (parts ? root : null), props: () => api.getRootProps() },
    { part: "control", node: () => parts?.control, props: () => api.getControlProps(), events: true },
    {
      part: "input",
      node: () => parts?.input,
      /* The authored name is restored over the machine's own props: without it the entry, which is
         the control a reader actually lands on, has no accessible name at all. */
      props: () => ({ ...api.getInputProps(), "aria-label": authoredLabel }),
      events: true,
    },
    { part: "hidden", node: () => parts?.hidden, props: () => api.getHiddenInputProps() },
  ];

  bindParts(bindings);
</script>

<!--
  THE LIVE LIST. It is mounted here, at the end of the root, and moved into the control on mount
  (see the hand-over above): a Svelte component renders where it is mounted, and where these belong
  is inside the field, before the entry.
-->
<span bind:this={renderedList} class={tagsInputParts.list} {...{ [tagsInputAttrs.list]: "" }}>
  {#each api.value as tag, index (`${tag}-${index}`)}
    <span {...api.getItemProps({ index, value: tag })} class={tagsInputParts.item}>
      <!-- The chip IS a Tag, composed rather than redrawn: see the contract's own header. -->
      <span
        {...api.getItemPreviewProps({ index, value: tag })}
        class="{tagsInputParts.preview} {tagParts.root}"
        data-removable=""
      >
        <span {...api.getItemTextProps({ index, value: tag })} class="{tagsInputParts.text} {tagParts.label}">
          {tag}
        </span>
        <!-- The same system-owned Button + close icon the emitted markup writes, and that Tag's own
             remove control is: the state layer, the focus ring and the hit target come with it. -->
        <button
          {...api.getItemDeleteTriggerProps({ index, value: tag })}
          class="{tagsInputParts.remove} {tagParts.remove} sk-button sk-interactive"
          aria-label={removeLabel}
          type="button"
          data-variant="ghost"
          data-tone="neutral"
          data-size="sm"
          data-icon-only=""
          data-sk-button=""
        >
          <span data-sk-icon="close" data-sk-icon-size="md"></span>
        </button>
      </span>
      <input {...api.getItemInputProps({ index, value: tag })} class={tagsInputParts.itemInput} />
    </span>
  {/each}
</span>

// packages/react/src/components/tags-input.tsx
import { tagsInput } from "@skryensya/core/machines";
import { tagParts } from "@skryensya/core/tag";
import {
  tagsInputContract,
  tagsInputEvents,
  tagsInputParts,
} from "@skryensya/core/tags-input";
import { normalizeProps, useMachine } from "@zag-js/react";
import { useId, useRef } from "react";
import { Button } from "./button.js";
import { Icon } from "./icon.js";

/* Derived, never restated: the defaults live in the contract. */
const {
  delimiter: delimiterOption,
  editable: editableOption,
  removeLabel: removeLabelOption,
} = tagsInputContract.options;

const cx = (base: string, className: string | undefined) => (className ? `${base} ${className}` : base);

export type TagsInputProps = {
  id?: string;
  /**
   * The accessible name of the entry. Required: with no name a screen reader announces an edit
   * field and nothing about what goes in it.
   */
  label: string;
  placeholder?: string;
  /** Every delete control's accessible name. One string for all of them; see the contract's note. */
  removeLabel?: string;
  /** The tags it starts with. Uncontrolled. */
  defaultValue?: string[];
  /** The tags, controlled. Spread conditionally: see the note inside. */
  value?: string[];
  /** How many tags the field accepts. Past it a new tag is refused in silence; see the contract. */
  max?: number;
  /** The character that both commits a tag and splits a pasted list. */
  delimiter?: string;
  allowDuplicates?: boolean;
  /** Whether a committed tag can be reopened (Enter, or a double click) and rewritten in place. */
  editable?: boolean;
  name?: string;
  disabled?: boolean;
  readOnly?: boolean;
  invalid?: boolean;
  required?: boolean;
  className?: string;
  onValueChange?: (details: { value: string[] }) => void;
};

/**
 * Several values typed into one field.
 *
 * It accepts whatever was typed, which is the whole difference from a Combobox: that one resolves
 * what is typed to one of its own options, and this one takes the person's own vocabulary.
 */
export function TagsInput({
  allowDuplicates,
  className,
  defaultValue,
  delimiter = delimiterOption.default,
  disabled,
  editable = editableOption.default,
  id,
  invalid,
  label,
  max,
  name,
  onValueChange,
  placeholder,
  readOnly,
  removeLabel = removeLabelOption.default,
  required,
  value,
}: TagsInputProps) {
  const generatedId = useId();
  const resolvedId = id ?? generatedId;
  const rootRef = useRef<HTMLDivElement>(null);

  /*
   * SPREAD, NOT `value: undefined`.
   *
   * `@zag-js/core`'s `bindable` reads controlled-vs-uncontrolled off the presence of the KEY, not
   * off the value being defined, so passing `value` unconditionally pins an uncontrolled field at
   * its initial tags forever: the callbacks still fire and nothing is ever added. The Rating
   * binding carries the same note, measured against the machine rather than guessed.
   */
  const service = useMachine(tagsInput.machine, {
    id: resolvedId,
    name,
    ...(value === undefined ? {} : { value }),
    ...(defaultValue === undefined ? {} : { defaultValue }),
    ...(max === undefined ? {} : { max }),
    delimiter,
    allowDuplicates,
    editable,
    disabled,
    readOnly,
    invalid,
    required,
    onValueChange(details) {
      onValueChange?.({ value: details.value });
      /* The same channel authored markup gets, with the same detail. */
      rootRef.current?.dispatchEvent(
        new CustomEvent(tagsInputEvents.valueChange, { bubbles: true, detail: { value: details.value } }),
      );
    },
  });
  const api = tagsInput.connect(service, normalizeProps);

  return (
    <div
      {...api.getRootProps()}
      className={cx(tagsInputParts.root, className)}
      data-disabled={disabled ? "" : undefined}
      data-invalid={invalid ? "" : undefined}
      data-readonly={readOnly ? "" : undefined}
      data-required={required ? "" : undefined}
      ref={rootRef}
    >
      <div {...api.getControlProps()} className={tagsInputParts.control}>
        {/* The node that stands for the whole list. `display: contents`, so it adds no box. */}
        <span className={tagsInputParts.list}>
          {api.value.map((tag, index) => {
            const item = { index, value: tag };

            return (
              <span {...api.getItemProps(item)} className={tagsInputParts.item} key={`${tag}-${index}`}>
                {/* THE CHIP IS A TAG, composed rather than redrawn: see the contract's own header. */}
                <span
                  {...api.getItemPreviewProps(item)}
                  className={`${tagsInputParts.preview} ${tagParts.root}`}
                  data-removable=""
                >
                  <span
                    {...api.getItemTextProps(item)}
                    className={`${tagsInputParts.text} ${tagParts.label}`}
                  >
                    {tag}
                  </span>
                  {/* A real Button, like Tag's own remove control: state layer, focus ring, hit target. */}
                  <Button
                    {...api.getItemDeleteTriggerProps(item)}
                    aria-label={removeLabel}
                    className={`${tagsInputParts.remove} ${tagParts.remove}`}
                    iconOnly
                    size="sm"
                    variant="ghost"
                  >
                    <Icon name="close" />
                  </Button>
                </span>
                <input {...api.getItemInputProps(item)} className={tagsInputParts.itemInput} />
              </span>
            );
          })}
        </span>
        <input
          {...api.getInputProps()}
          aria-label={label}
          className={tagsInputParts.input}
          placeholder={placeholder}
        />
      </div>
      <input {...api.getHiddenInputProps()} className={tagsInputParts.hidden} />
    </div>
  );
}
